### ISSUE TITLE
Error when allowing player to reuse a tool

### ISSUE THREAD

**Issue by jimmysmith1** [FPtje/Falcos-Prop-protection#100]
After a week of having aplayer banned from using E2, we went to unban him. This error flashed up while doing it. 

[ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:721: attempt to perform arithmetic on local 'a' (a string value)
  1. DoClick - gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:721
   2. OnMouseReleased - lua/vgui/dlabel.lua:206
    3. unknown - lua/vgui/dmenuoption.lua:116

**Comment by FPtje** [comment]
I can't reproduce this bug. Instead I've made it give an OK message when you actually set the restrictions. This gives confirmation that it works.
