### ISSUE TITLE
Usergroups spawning blacklisted props

### ISSUE THREAD

**Issue by Yoddo** [FPtje/Falcos-Prop-protection#102]
All my usergroups but superadmin can spawn blacklisted props. I see no error in console of the server and i have no idea how the problem was created and i have no idea how to fix it. Please help me

**Comment by FPtje** [comment]
It's probably a conflicting addon. I've already identified URS as a potential allfucker.

**Comment by Yoddo** [comment]
And how do i fix this problem because i do not have any props blocked with URS, all i use URS for is restrict tools

**Comment by FPtje** [comment]
Urs fucks shit regardless

**Comment by Yoddo** [comment]
Ive tried spawning some blacklisted props, some can be spawned and some cant i have no idea what is going on. What should i do? reinstall URS?
