### ISSUE TITLE
FPP on Ubuntu Garrysmod server

### ISSUE THREAD

**Issue by THE-HAVOK** [FPtje/Falcos-Prop-protection#104]
After installing FPP onto my sandbox garrysmod server running on Ubuntu players who joined the server would stop at retrieving server info. server throws no errors nor clients
both workshop and legacy versions tried with failure on both.

**Comment by FPtje** [comment]
I cannot reproduce this on Arch Linux.

**Comment by FPtje** [comment]
I can't reproduce this on a Windows dedicated server either. I think there's something else wrong with the server.
