### ISSUE TITLE
Owner bug with some Scripted Entities

### ISSUE THREAD

**Issue by flydvorkin** [FPtje/Falcos-Prop-protection#105]
With use addon:
http://steamcommunity.com/sharedfiles/filedetails/?id=261801217
some scripted entities are spawned with different owner of parts of the entity.
For exapmle when spawn "Train bodgey", some parts of this entity (frame) are ownered as "world" (screenshot №1) or not ownered (screenshot №2), but other parts (wheels) are correct ownered by self username (screenshot №3).
As a result this entity can't use by physgun if i looked at "world"-ownered or not-ownered part of entity.
Also this bug bring to nex bug: If this train bodbey are coupling with other bodgey or train (initially all parts of the train include train bodgey are ownered correctly, screenshot №4), owner of the train and owner of initially correct ownered part of bodbey are changed to red "constrained" (screenshot №5).

This situation are may partially fixed when look of bugged parts of the train bodgey and add this entity to physgun block list (owner of all parts of bodgey are changed to "blocked") and remove it from block-list, then all parts of entity are correct ownered by self username. But this is required admin-permissions to manage FPP settings and not resolve situation.

Screenshots:
1) http://hostingkartinok.com/show-image.php?id=35b089f8590de938ad6e37316def439e
2) http://hostingkartinok.com/show-image.php?id=166a832bf3ec5811807cf34e1ff52999
3) http://hostingkartinok.com/show-image.php?id=2e9611905487594ef97a9af9e317bd86
4) http://hostingkartinok.com/show-image.php?id=44c9a22334f480b6ddee7847608e3def
5) http://hostingkartinok.com/show-image.php?id=3abbb2e459bf0eca2f4904c14ae774e0

**Comment by FPtje** [comment]
All modern prop protections have this common interface called CPPI. People who make entities that consist of other entities are responsible for calling CPPI to set the proper owner of the model.

Once the authors of this addon fix CPPI, it will be fixed for ALL prop protection addons. This is their responsibility.

**Comment by flydvorkin** [comment]
But with other protection addons - no bugs

**Comment by flydvorkin** [comment]
Can you answer - why with other protection addons (SPP, Nadmod) this bug is not present?

**Comment by FPtje** [comment]
I don't know, but when I tried spawning some of the entities in my own game
I did see the owner properly.
