### ISSUE TITLE
Vehiclse thru Car-Dealer spawn as "constrained" for user in Group "user"

### ISSUE THREAD

**Issue by SeaLife** [FPtje/Falcos-Prop-protection#107]
Hey, since the Update, my car dealer fails to spawn cars for they real Owner...

The always spawn as "constrained"...

ent:CPPISetOwner( ply ) did not even help...

Can you tell me how to spawn a car in DarkRP/FPP for the owner (ply), that he can pickup his car and modify it with Toolgun/Propertys..

Car Dealer:

http://pastebin.com/egvytqde

Buyer = Player object of the Buyer

**Comment by FPtje** [comment]
That bit's working, but you need to set the owner of the constrained entities too.

**Comment by SeaLife** [comment]
Hey, there are no constrained entities...

Only the "Car" spawns...

Before the gmod update (09.03) it works perfectly...

http://grp-c.de/carbug.png

**Comment by FPtje** [comment]
FPP says there are.

**Comment by SeaLife** [comment]
ok, thank you... i just restarted my brain.. and... OH!! Passenger Mod... The Seats... Constrained Entities... o.o

But it worked before... nvm, i dont care, fixxed it now.. :D :) :+1:

THANK YOU :+1:
