### ISSUE TITLE
Netchannel: unknown net message (45)

### ISSUE THREAD

**Issue by Bryantdl7** [FPtje/Falcos-Prop-protection#108]
I found #97 which seems to be a similar problem, however in my case I do have some errors. 
Hopefully this is a simpler fix as my server cannot be connected to currently. 

Netchannel: unknown net message (45) from 192.223.26.64:27015.
ConVarRef _FPP_ANTISPAM1_duplicatorlimit doesn't point to an existing ConVar
ConVarRef _FPP_PHYSGUN1_worldprops doesn't point to an existing ConVar

**Comment by Bo98** [comment]
Does it happen without FPP though?

**Comment by Bryantdl7** [comment]
When I uninstall FPP I can connect yes. FA:S is causing the conflict, however this isn't the first addon to do this. An addon called buildmode would also trigger this error.

**Comment by FPtje** [comment]
https://github.com/FPtje/Falcos-Prop-protection/issues/97#issuecomment-67297593 remains valid.

**Comment by Bryantdl7** [comment]
I wrote the authors of the addons that conflict, if you would like to make any comments along with what I said, here are the discussion links.
 
http://steamcommunity.com/workshop/filedetails/discussion/372546268/618458030650722715/
http://steamcommunity.com/workshop/filedetails/discussion/180507408/618458030650720139/
