### ISSUE TITLE
Reset settings?

### ISSUE THREAD

**Issue by deadlyshot02** [FPtje/Falcos-Prop-protection#112]
How can I reset to default settings? I already replaced the darkrp folder, and nothing, this is VERY annoying, please help me!

**Comment by FPtje** [comment]
They're stored in sv.db. You must have copied that over too.

**Comment by FPtje** [comment]
Maybe a command for it would be very useful.

I've added it in the latest beta of FPP. The command is `FPP_ResetAllSettings`.

**NOTE** This is a beta version of FPP That is **NOT** on the workshop yet. I made quite a few improvements that will make FPP more efficient in the settings department. Please test it by downloading it from github, which is here:
https://github.com/FPtje/Falcos-Prop-protection/archive/master.zip

**Comment by brandonsturgeon** [comment]
Is this command still supported? `FPP_ResetAllSettings` gives no output and doesn't appear to affect the existing groups and such.

I'd just like a factory-fresh FPP install.

**Comment by Bo98** [comment]
It should be. It should be giving a standard FPP notification upon completion, unless there's some error with the database transaction which will be noted as a Lua error in the server console.

**Comment by brandonsturgeon** [comment]
My mistake, it does in fact exist and return output.

However, it doesn't clear all of the data. For example, the toolgun restriction groups remain after running the command. Is this intended behavior or an oversight? I'd be happy to throw up a PR.
