### ISSUE TITLE
Can't interact with constrained props when removing one in a contraption

### ISSUE THREAD

**Issue by logan2611** [FPtje/Falcos-Prop-protection#113]
So when I remove a part of a contraption, I suddenly can't interact with it. My names turns red and nothing works. Not even superadmins on the server can touch it. It isn't a server specific issue either because I have had this problem on multiple servers.

**Comment by FPtje** [comment]
Give me specific steps to reproduce

**Comment by logan2611** [comment]
Alright, I think this only happens with SBEP entities, but I am not sure exactly.
1. Spawn contraption
2. Remove something
3. Bam. Can't do anything

**Comment by FPtje** [comment]
![2015-05-17_15-08-58](https://cloud.githubusercontent.com/assets/1202014/7670088/0ad7acb6-fc96-11e4-9e00-e6819a5c44d3.jpg)
![2015-05-17_15-09-09](https://cloud.githubusercontent.com/assets/1202014/7670089/0bdf878c-fc96-11e4-8efd-3200d72b39bb.jpg)
![2015-05-17_15-09-14](https://cloud.githubusercontent.com/assets/1202014/7670090/0cec91f6-fc96-11e4-82b0-695a7259211d.jpg)
![2015-05-17_15-09-26](https://cloud.githubusercontent.com/assets/1202014/7670091/0e1623c6-fc96-11e4-8807-5477c796eba6.jpg)
![2015-05-17_15-09-33](https://cloud.githubusercontent.com/assets/1202014/7670092/0fe4c7a2-fc96-11e4-9ce9-e0635408dd34.jpg)
Cannot reproduce.
