### ISSUE TITLE
Add 'Ignore Admins' in antispam module?

### ISSUE THREAD

**Issue by 00875** [FPtje/Falcos-Prop-protection#115]
Can you add 'Ignore Admins' in Antispam module?

**Comment by FPtje** [comment]
FUCK no, you selfish bastard

**Comment by 00875** [comment]
Very fun reply.

**Comment by FPtje** [comment]
I'm fucking serious. 
http://facepunch.com/showthread.php?t=1463586&p=47649531&viewfull=1#post47649531

**Comment by 00875** [comment]
Okay. Thanks, now i know why you don't make this option.
