### ISSUE TITLE
sv_doorvars.lua:148: Table doesn't contain any valid entities!

### ISSUE THREAD

**Issue by anyome** [FPtje/Falcos-Prop-protection#117]
Hello,
After the new garry's mod udpate, i start getting this error message:
[ERROR] gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:148: Table doesn't contain any valid entities!
  1. Send - [C]:-1
   2. updateDoorData - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:148
    3. addKeysDoorTeam - gamemodes/darkrp/gamemode/modules/doorsystem/sv_doorvars.lua:37
     4. callback - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:361
      5. query - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:154
       6. setUpTeamOwnableDoors - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:354
        7. onFinished - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:152
         8. commit - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:68
          9. initDatabase - gamemodes/darkrp/gamemode/modules/base/sv_data.lua:149
           10. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:85
            11. unknown - gamemodes/darkrp/gamemode/libraries/mysqlite/mysqlite.lua:38

Does anyone know how to fix it please!?

Line 148 is: net.Send(player.GetAll())

function DarkRP.updateDoorData(door, member)
	if not IsValid(door) or not door:getDoorData() then error("Calling updateDoorData on a door that has no data!") end

	net.Start("DarkRP_UpdateDoorData")
		net.WriteUInt(door:EntIndex(), 32)
		net.WriteString(member)
		net.WriteType(door:getDoorData()[member])
	net.Send(player.GetAll())
	--net.Send( team.GetPlayers( x ) )
end

**Comment by FPtje** [comment]
http://facepunch.com/showthread.php?t=1450721&p=47852133&viewfull=1#post47852133

**Comment by anyome** [comment]
same error here

**Comment by anyome** [comment]
team.getplayers(x) don't works

**Comment by FPtje** [comment]
Your readings skills don't either.

**Comment by anyome** [comment]
plz falco help me

**Comment by FPtje** [comment]
Go to the god damn forums and don't bother me.
