### ISSUE TITLE
(as requested by developer) FPP not tool-protecting this vehicle 

### ISSUE THREAD

**Issue by Bryantdl7** [FPtje/Falcos-Prop-protection#120]
Basically the addon owner says the reason the vehicle he made can be deleted by anyone is because of fpp.

Comments greatly appreciated 

http://steamcommunity.com/workshop/filedetails/discussion/118997241/530646080859988520/

**Comment by FPtje** [comment]
See my reply.

**Comment by Bryantdl7** [comment]
Thanks for helping, for one of the most popular addon developers in all of gmod you have no idea how awesome it is to end users that you help with issues like the one mentioned above.

**Comment by FPtje** [comment]
This is something you're not responsible for. Either way I would still like
to know how you spawn it. Is it the q menu,  f4 menu or something else?

**Comment by Bryantdl7** [comment]
Q menu/vehicles/hl2 vehicles
