### ISSUE TITLE
[Improvement] Allow admins to not apply to anti spam

### ISSUE THREAD

**Issue by Bryantdl7** [FPtje/Falcos-Prop-protection#124]
Currently, anyone with the admin rank still has large props ghost just like other users. This is something that I feel shouldn't happen, as admins are typically trustworthy and should not have the same anti spam fail-safe as the random guest that joins my server. 
I'm aware FPP already has a lot of features but I feel there should be a way to allow admins to be immune to anti spam protection.

**Comment by FPtje** [comment]
Not in there because it makes admins oblivious of the anti spam, letting them set the settings to ridiculous levels. It's what happened with ass antispam. I swore never to make this option.

**Comment by FPtje** [comment]
Have a rant on it:
http://facepunch.com/showthread.php?t=1463586&p=47649531&viewfull=1#post47649531
