### ISSUE TITLE
FPP - Unknown commands, settings not saving

### ISSUE THREAD

**Issue by Pierloch** [FPtje/Falcos-Prop-protection#126]
I am running a darkrp server for me and some friends. Every time someone joins the server, the console is flooded with unknown FPP commands.

![console](https://cloud.githubusercontent.com/assets/4983378/8974468/f5a4190e-363f-11e5-8f13-a912ef00cfcd.png)

Not only that, but if I go in game to the settings for FPP under the Q menu, it will allow me to make changes to the settings and such, but as soon as I leave the menu and return, the settings have reverted back to the way they were before I changed them.
I used both the file system addon version of FPP and the workshop version, separately. I hope someone is able to help me with this issue. Thank you.

**Comment by FPtje** [comment]
FPP has removed the cause of such errors quite a while ago (May 8th). I don't know where you're getting your FPP from, but it's out of date.

Get FPP from either here:
http://steamcommunity.com/sharedfiles/filedetails/?id=133537219

or this very Github repository.

**Comment by Pierloch** [comment]
Thank you for your help :)

**Comment by Pierloch** [comment]
I got my FPP from this repo. I even tried downloading it again in case there was some form of issue. I also deleted the addon folder and used the workshop addon. Same thing is happening. Any change I make in the Q menu, it's an unknown command in the console, and no changes are saved.
