### ISSUE TITLE
ULX Support

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/Falcos-Prop-protection#132]
I would suggest to add ulx(fadmin) support, just because superadmins now are joking with settings etc.

**Comment by FPtje** [comment]
Ulx will implement CAMI in time. Be patient.

**Comment by deinemudda32** [comment]
I mean support for restricting things for SAdmin, some for admins, some for the "owner" group if it exists.

**Comment by FPtje** [comment]
Remove `SetAccess` from superadmin, `ServerSetting` and `changelevel` if you like. FAdmin will NEVER try to share those privileges with other admin mods.

**Comment by deinemudda32** [comment]
(Already have that)

I meant youre Prop protection, this isnt the DarkRP Thread ;).

**Comment by FPtje** [comment]
Will be added when CAMI is somewhat more widely adopted.

**Comment by FPtje** [comment]
Fuck it

**Comment by deinemudda32** [comment]
What does "Fuck it" mean? Im irritated!

**Comment by FPtje** [comment]
I reopened the issue. I'm working on it right now.

**Comment by FPtje** [comment]
CAMI support is now in beta on the master branch. Try it out. I've only done the changing of settings and cleaning up props. I'd have to edit too much to get the "admins can pickup other players' shit" thing integrated with CAMI.
