### ISSUE TITLE
Crashs Game

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/Falcos-Prop-protection#134]
If you try to open settings, the game does crash.
Since update.

Additional Info:
Using ULX
Running Gamemode Sandbox

**Comment by FPtje** [comment]
![2015-08-24_21-05-36](https://cloud.githubusercontent.com/assets/1202014/9449606/e8b3235c-4aa3-11e5-94c5-5eb2d9d952de.jpg)

Nope.

**Comment by deinemudda32** [comment]
Why the heck does this shit happen then...

**Comment by FPtje** [comment]
FPP abides nicely by GMod's API rules. If opening an FPP menu crashes your game, then either your installation is fucked or there's a bug in GMod that only applies to you.

Either way I should stay clear.

**Comment by deinemudda32** [comment]
It doesnt only happen to me.
Happens to everyone.
Works in DarkRP, but not on my sandbox server however.

**Comment by FPtje** [comment]
Please, read my previous post again

**Comment by FPtje** [comment]
I'm not responsible for any crashes. You are done here.
