### ISSUE TITLE
FPP_Settings

### ISSUE THREAD

**Issue by itswonky** [FPtje/Falcos-Prop-protection#135]
I have the updated SVN for ulx, ulib, and fpp. Even though I am superadmin, I can't blacklist, whitelist, or change FPP settings like toolrestriction. I have reinstalled ulx, ulib, fpp, and also tried using the workshop fpp, but I still haven't fixed it. It said I need FPP_Settings so in "data\ulib\groups.txt" I added "FFP_Settings" under allow for superadmin, yet it still doesn't work! I really need this fixed for my server.
Thank you for your time.

**Comment by FPtje** [comment]
What happens when you add FPP_Settings to superadmin in the ULX menu rather than some text file?

**Comment by itswonky** [comment]
Okay so I did "ulx groupallow superadmin FPP_Settings" because the command wasn't in the ULX menu. I was able to blacklist, but it still said I didn't have access, then it would blacklist it.
https://i.gyazo.com/58932e624c804feceecf7412c5c4bb5f.png
The biggest problem is I still can't change FPP settings as they are grayed. 
https://i.gyazo.com/07b40c63064547f42407c894874d0dd6.png

**Comment by FPtje** [comment]
Try seeing if everything is alright in this menu
![2015-08-25_16-41-20](https://cloud.githubusercontent.com/assets/1202014/9469589/368a336e-4b48-11e5-9a75-df7d9ac1ffec.png)

I can't reproduce this on my listen server, now checking dedi server

**Comment by itswonky** [comment]
Nothing is here for fpp :/
![](https://i.gyazo.com/e3937de2d347cc35606c1b0629c78cc4.png)

**Comment by FPtje** [comment]
Please see that ULib issue. It's a CAMI problem :)

**Comment by FPtje** [comment]
You're lucky that there's this other bug that allows you to do it anyway: the two messages, with one saying you can't and another saying you can. It makes you able to live with it for now.
