### ISSUE TITLE
Make use of PlayerSpawnObject Hook where Possible

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/Falcos-Prop-protection#136]
Would it be possible to make use of the [PlayerSpawnObject] (http://wiki.garrysmod.com/page/SANDBOX/PlayerSpawnObject) hook for checking whether a Prop is allowed to be spawned or not, and wherever else possible?

I ask for this as currently, attempting to spawn a prop that is blacklisted (or not whitelisted) will still have the Engine precache the model. The `modelprecache` stringtable can only hold 2048 models, after which any more that attempt to be precached will cause an overflow and crash the Engine (on a server, this means a server crash).

Here is a demonstration:
```
ServerLog: The Amazing Spider Pone (STEAM_0:1:46836119) Spawned a models/props_c17/FurnitureCouch001a.mdl
Spawn: Model Precache has Updated! | Count: 851

ServerLog: The Amazing Spider Pone (STEAM_0:1:46836119) Spawned a models/props_c17/FurnitureCouch002a.mdl
Spawn: Model Precache has Updated! | Count: 852

ServerLog: The Amazing Spider Pone (STEAM_0:1:46836119) Spawned a models/props_c17/FurnitureTable002a.mdl
Spawn: Model Precache has Updated! | Count: 860

ServerLog: The Amazing Spider Pone (STEAM_0:1:46836119) Spawned a models/props_c17/furnitureStove001a.mdl
Spawn: Model Precache has Updated! | Count: 861

The model of this entity is in the black list!

ServerLog: The Amazing Spider Pone (STEAM_0:1:46836119) Spawned a models/props_c17/gravestone_statue001a.mdl
Spawn: Model Precache has Updated! | Count: 863

ServerLog: The Amazing Spider Pone (STEAM_0:1:46836119) Spawned a models/props_borealis/mooring_cleat01.mdl
Spawn: Model Precache has Updated! | Count: 864

The model of this entity is in the black list!

ServerLog: The Amazing Spider Pone (STEAM_0:1:46836119) Spawned a models/props_c17/bench01a.mdl
Spawn: Model Precache has Updated! | Count: 866
```
Whenever a new prop is spawned, if its model isn't already precached in the `modelprecache` string table, the Engine will automatically do so, hence why the count incremented by 1 each time I spawned in a new prop.

`models/props_c17/FurnitureTable002a.mdl` has gibs, which also get automatically precached when spawned. This is why the count jumped from ***852*** to ***860***.

The two blacklisted props above were `models/props_c17/oildrum001_explosive.mdl` and `models/Cranes/crane_frame.mdl` used as examples. They were not allowed to be spawned, however the count incremented by ***2*** when the next model precache count was printed. This is due to the blacklisted props getting precached, despite they were not allowed to be spawned in.

From testing, I have observed this occurs if you use the [PlayerSpawnEffect] (http://wiki.garrysmod.com/page/SANDBOX/PlayerSpawnEffect), [PlayerSpawnProp] (http://wiki.garrysmod.com/page/SANDBOX/PlayerSpawnProp) and [PlayerSpawnRagdoll] (http://wiki.garrysmod.com/page/SANDBOX/PlayerSpawnRagdoll) hooks. `PlayerSpawnObject` however, can be used to check if the player is attempting to spawn any 3 of these entity types, whilst also not having the model(s) of the prop get precached, but it ***is not called when spawning in a Dupe***.

All of the above hooks can be used in conjunction with one another however, so that's something at least. I'd really appreciate it if you could make use of `PlayerSpawnObject` attempt to keep the modelprecache table filling up as slowly as possible. Use of `PlayerSpawnObject` can also be used to prevent bad models from getting precached, causing the server to instantly crash.

Feel free to question me etc. if needed. I can understand if this seems a bit whacky. I'm happy to assist in any way possible.

**Comment by FPtje** [comment]
Oh wait I see it now, PlayerSpawnObject is called right before `util.IsValidModel`, which precaches the model

**Comment by Hazbelll** [comment]
Thank you kindly for implementing this!
