### ISSUE TITLE
FPP doesn't think I'm admin, yet is allowing commands

### ISSUE THREAD

**Issue by Bryantdl7** [FPtje/Falcos-Prop-protection#138]
The photo describes it better than I could ever. My permissions are fine, this just started happening when I deleted FPP and redownloaded it. I have deleted and gotten a fresh download again since the  problem started.

![image](https://cloud.githubusercontent.com/assets/5564661/9701529/bf4e2762-53fb-11e5-8e85-24e0f163711d.png)

**Comment by FPtje** [comment]
That's a ulx bug
