### ISSUE TITLE
Add a option to freeze player entities on his disconnect.

### ISSUE THREAD

**Issue by 00875** [FPtje/Falcos-Prop-protection#139]
It would prevent this:
1. Minge joined server
2. Minge spawns tons of shit
3. Server lagging
4. Minge leaving the server
5. Make his shit frozen and server is no more lagging

**Comment by FPtje** [comment]
What should be done with entities that shouldn't be frozen?

**Comment by 00875** [comment]
Nothing. It just prevent server from lagging when player leave. This extends 'Delete on disconnect' function

**Comment by deinemudda32** [comment]
Mostly minges don't disconnect :)
