### ISSUE TITLE
Superadmins immune to world protection

### ISSUE THREAD

**Issue by Bryantdl7** [FPtje/Falcos-Prop-protection#143]
Anyone with the rank of superadmin or higher can always touch world props unless they are blacklisted props, is there a way I can disable this ability?

Side note; setting up a wiki for FPP would be absolutely amazing.

**Comment by FPtje** [comment]
Yes. There's an option in the menu that says "admins can touch world props".  Do I really need to write a wiki for you to understand this?

**Comment by Bryantdl7** [comment]
I have admins can touch world props unchecked. I assumed it was because I have the rank of super admin, as admins below super admin can't touch world props.

**Comment by FPtje** [comment]
No, FPP does not commit to such nonsense.
