### ISSUE TITLE
Superadmins immune to world protection, (added specifics this time)

### ISSUE THREAD

**Issue by Bryantdl7** [FPtje/Falcos-Prop-protection#144]
In the first screenshot I am at a rank that has rights of the ulib rank admin. As you can see, I cannot touch the world prop.
![image](https://cloud.githubusercontent.com/assets/5564661/10929060/a73224b2-827c-11e5-90ea-a628db8d915c.png)
In the second photo I am in a rank that has the rights of the ulib rank superadmin, notice how I can grab the prop.

![image](https://cloud.githubusercontent.com/assets/5564661/10929079/d9adf790-827c-11e5-9aed-b656cf807a04.png)

My question is, is this supposed to happen, and is there a way I can disable this. 

Even selecting I don't want to touch world props isn't solving this.

![image](https://cloud.githubusercontent.com/assets/5564661/10929102/38f3fad8-827d-11e5-9eee-82586d49afa6.png)

I apologize for the poorly written issue earlier, I was trying to get it posted before I left for work.

**Comment by FPtje** [comment]
Duplicate issue to grab attention. 

It's not FPP.
