### ISSUE TITLE
World Props

### ISSUE THREAD

**Issue by anonymous123456789** [FPtje/Falcos-Prop-protection#145]
On my DarkRP server all props when spawned in are world props and you cant remove them with "Z" you have to remove them with your remove tool gun tool, please help

**Comment by FPtje** [comment]
Not a help forum.

**Comment by anonymous123456789** [comment]
Where can i get help ?

**Comment by FPtje** [comment]
https://facepunch.com/forumdisplay.php?f=16

**Comment by FPtje** [comment]
Your post on the DarkRP forums helps too.

**Comment by anonymous123456789** [comment]
Ok, thanks
