### ISSUE TITLE
"You need "FPP_Settings" privilege" as superadmin

### ISSUE THREAD

**Issue by nex86** [FPtje/Falcos-Prop-protection#146]
I can't change any settings in FPP and its telling me I need the  "FPP_Settings" privilege to be able to use this command.

I'am superadmin in ulx and I also can't find the permission FPP_Settings in manage groups/manage permissions.

**Comment by FPtje** [comment]
Make sure you have the latest version of ulx.

**Comment by nex86** [comment]
I have directly downloaded it from Github at https://github.com/Nayruden/Ulysses 2 days ago, so pretty sure I have the latest version.
