### ISSUE TITLE
ULX error

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/Falcos-Prop-protection#147]
[ERROR] addons/ulx/lua/ulib/shared/sh_ucl.lua:48: attempt to call method 'UniqueID' (a nil value)
  1. query - addons/ulx/lua/ulib/shared/sh_ucl.lua:48
   2. fn - addons/ulx/lua/ulib/shared/cami_ulib.lua:18
    3. Call - addons/ulx/lua/ulib/shared/hook.lua:110
     4. PlayerHasAccess - addons/fpp/lua/libraries/sh_cami.lua:370
      5. unknown - addons/fpp/lua/fpp/client/menu.lua:37

Happens on joining a server with fpp and ulx.

**Comment by FPtje** [comment]
ULX' problem, init?

**Comment by deinemudda32** [comment]
Isnt there some sort of hotfix?

**Comment by FPtje** [comment]
what, you want me to mess with ULX shit because they throw an error?

**Comment by deinemudda32** [comment]
Its a cami error.

**Comment by FPtje** [comment]
Yes, in ULX

**Comment by Bo98** [comment]
Looks like PlayerHasAccess is being passed a NULL value by FPP to me.

**Comment by FPtje** [comment]
Not to me, this is client/menu.lua:37..

```lua
CAMI.PlayerHasAccess(LocalPlayer(), "FPP_Settings", function(b, _)
        canEditSettings = b
    end)
```

That code gets called after InitPostEntity. `LocalPlayer` can't be null there.

**Comment by Bo98** [comment]
Where's the InitPostEntity part? All I have is a timer running on file load.

**Comment by FPtje** [comment]
That's it. `timer.Simple(0, ...` = on first Think tick. The first Think tick doesn't happen until during/after `InitPostEntity`.

**Comment by deinemudda32** [comment]
But why the hell does it work in DarkRP with ULX on and in Sandbox not?

**Comment by SticklyMan** [comment]
@FPtje ```LocalPlayer()``` is not null there, but for some reason we can't call ```UniqueID()``` on it at that point.  
Try adding ```print( LocalPlayer():UniqueID() )``` on line menu.lua:37, and you'll get the same error:
```
[ERROR] addons/falcos-prop-protection/lua/fpp/client/menu.lua:37: attempt to call method 'UniqueID' (a nil value)
  1. unknown - addons/falcos-prop-protection/lua/fpp/client/menu.lua:37
```

Changing the ```timer.Simple``` to instead hook on ```PlayerInitialSpawn``` seems to fix the issue, but I don't know if that will cause any side effects.

**Comment by FPtje** [comment]
Well yes, PlayerInitialSpawn is server side.

**Comment by SticklyMan** [comment]
Heh, whoops. So it is! I only had a few minutes to test this tonight, and I'm not the most familiar with these hooks.

**Comment by deinemudda32** [comment]
You could use the Networking Library if it will conflict anything.

**Comment by SticklyMan** [comment]
Now that I've had a good sleep, I changed it to hook on ```InitPostEntity```, and it looks like it's working properly. It would seem that ```LocalPlayer()``` isn't fully ready on first think tick?

**Comment by FPtje** [comment]
Looks like `timer.Simple(0, ...` is not the same as `InitPostEntity` anymore.

**Comment by SticklyMan** [comment]
Thanks!

**Comment by FPtje** [comment]
yes
