### ISSUE TITLE
E2 Antiminge bug

### ISSUE THREAD

**Issue by thegrb93** [FPtje/Falcos-Prop-protection#148]
Just looked at your e2 anti-minge code and it looks like it will run on things the e2 owner doesn't own.

**Comment by thegrb93** [comment]
Unless
```
local ent = args[2][1](self, args[2])
```
Does that check.

**Comment by FPtje** [comment]
It will affect anything that has force applied by the E2. It used to be a lot slower, but the latest update to it (quite a while ago now) made it a lot faster.

**Comment by thegrb93** [comment]
So I can spawn an e2 that does applyForce on anything in the server including other player's props and it's collision group will go to COLLISION_GROUP_WEAPON

**Comment by FPtje** [comment]
If I'm not mistaken, E2 checks CPPI before it runs that function. That means the answer is: no, you can't.

Try it if you want to be sure.

**Comment by thegrb93** [comment]
I don't have it installed and I'm getting off for now. Just thought I'd mention it because it doesn't look like there's any PP check cause I think the PP check applyforce uses is here https://github.com/wiremod/wire/blob/master/lua/entities/gmod_wire_expression2/core/entity.lua#L460.

**Comment by FPtje** [comment]
https://github.com/wiremod/wire/blob/9847ecf5bee18184fcc32d98738422961a2e6461/lua/entities/gmod_wire_expression2/core/e2lib.lua#L198

https://github.com/wiremod/wire/blob/9847ecf5bee18184fcc32d98738422961a2e6461/lua/entities/gmod_wire_expression2/core/e2lib.lua#L698

It checks CPPI.

**Comment by thegrb93** [comment]
Yes I know that their code checks CPPI, but your detour does not. I just tested it and I was able to make things I don't own into COLLISION_GROUP_WEAPON by doing e:applyForce on it.

**Comment by FPtje** [comment]
Can you give me the script?

**Comment by thegrb93** [comment]
entity(79):applyForce(vec(0,0,100000))
