### ISSUE TITLE
MySQL cannot be connect

### ISSUE THREAD

**Issue by MrTheBank** [FPtje/Falcos-Prop-protection#151]
I'm open Sandbox server and when i use MySQL it's say
addons/falcos-prop-protection-master/lua/libraries/mysqlite/mysqlite.lua:334: at temt to index upvalue "GAMEMODE" <a nil value> Can you fix it please

**Comment by FPtje** [comment]
Your game is broken. Every gamemode has a GAMEMODE table.

**Comment by MrTheBank** [comment]
Sandbox?

**Comment by FPtje** [comment]
yes, including sandbox.
