### ISSUE TITLE
Plugin won't mount

### ISSUE THREAD

**Issue by Krachbummente1337** [FPtje/Falcos-Prop-protection#152]
Hey Falco,

just wanted to ask whether there are some workarounds when the FPP script isn't mounted properly.
I have placed the latest "Falcos-Prop-protection-master" into my addon folder but it does not appear in the menu after restarting the server.
The log tells me that the folder is being mounted... but thats all.

When I tried the same procedure on a local dedicated server everything worked fine.
I have no idea why my gameserver refuses to load the script.

Both servers are using ULX 3.62 and ULib 2.52.
My online gameserver runs with uclip, some sTools and custom models - the listen server runs vanilla without any futher modifications.

Could there be collisions with some of these mods preventing the script from being initialized?

Greetings,
Krachbummente

**Comment by FPtje** [comment]
I don't give installation help on github. Github is for bugs and feature requests

**Comment by Krachbummente1337** [comment]
Thanks for the help! :)
