### ISSUE TITLE
FPP Logs

### ISSUE THREAD

**Issue by RonnieeTV** [FPtje/Falcos-Prop-protection#154]
Superadmins on our Server currently keep blacklisting props, I was wondering if there were any Logs to where I can find who keeps blacklisting props?

Thanks

**Comment by FPtje** [comment]
I don't think blocked props are logged.

**Comment by RonnieeTV** [comment]
Alright thanks, is there any way to enable logging for blocked props?
Or possibly a future feature to add?

Thanks FPtje.
