### ISSUE TITLE
Issue with restriction. 

### ISSUE THREAD

**Issue by MrEASlol** [FPtje/Falcos-Prop-protection#156]
Hello, im currently running a server using your mod and for some reason, when i try to restrict wiremod tools, it refuses to save. We found an error within the servers console. This server runs DarkRP.

Error sending usermessage - too large (FPP_RestrictedT)Error sending usermessage - too large (FPP_RestrictedT)Error sending usermessage - too large (FPP_RestrictedT)

We have tried reinstalling FPP to fix the problem, but no luck, . Any help?

**Comment by FPtje** [comment]
Which wiremod tools specifically?

**Comment by MrEASlol** [comment]
All of them, im trying to restrict all wiremod tools to two specific jobs. We're also using wiremod extras svn.
