### ISSUE TITLE
WAC Constrained

### ISSUE THREAD

**Issue by Zaddion** [FPtje/Falcos-Prop-protection#159]
I'm having an issue with WAC being "constrained" to non-admins:
http://steamcommunity.com/sharedfiles/filedetails/?id=104990330
http://steamcommunity.com/sharedfiles/filedetails/?id=108907015

Is there a way I can allow my players to use their physgun on their WAC Aircraft? They can use their toolgun on it. I apologize if this issue has been brought up before, I couldn't find it anywhere.

**Comment by FPtje** [comment]
It's WAC's responsibility to assign ownership to sub-entities through CPPI.
