### ISSUE TITLE
Players can unfreeze others props

### ISSUE THREAD

**Issue by Tendersexpartner** [FPtje/Falcos-Prop-protection#162]
you never helped me in here.  https://github.com/FPtje/Falcos-Prop-protection/issues/161 
you said it was a bad config bad config with what?
is it falcos or something else. actually helping would be great thanks

**Comment by FPtje** [comment]
Hey if I close an issue, you don't nag me in both that issue and a fucking new one. This is an issue tracker, not a "please help me I've turned an option off and now I don't know how to solve that" website.
