### ISSUE TITLE
Freezes my game when clicking on admin settings

### ISSUE THREAD

**Issue by HG-Josh** [FPtje/Falcos-Prop-protection#163]
I was told this was fixed but it still occurs for me, WHen I click on the admin tab my game freezes

**Comment by FPtje** [comment]
Cannot reproduce.

**Comment by FNCxPro** [comment]
Could you possibly spend a tiny bit more time on this? It's happening for me also.

**Comment by FPtje** [comment]
When did you last update fpp and where did you get it from?

**Comment by FNCxPro** [comment]
I got FPP from the DarkRP 2.6.1 release, last updated when I downloaded the DarkRP 2.6.1 release.
I downloaded the DarkRP 2.6.1 release from the GitHub repository.

**Comment by FPtje** [comment]
I don't support that version anymore.

**Comment by FNCxPro** [comment]
Alright I will update it...

**Comment by Bo98** [comment]
@FPtje You should probably delete that 2.6.1 release (`pre-2.6.2` tag) as its removal is well overdue.
