### ISSUE TITLE
Console Commands

### ISSUE THREAD

**Issue by Regrave** [FPtje/Falcos-Prop-protection#165]
Is there any Console Commands to set someone to have access to a certain tool? Something like:

fpp_addusertoolrestriction (SteamID)
or,
fpp_removeusertoolrestriction (SteamID)

I really wish this was a thing, and I also hope you'd be able to implement this into FPP. Anyway, I guess this isn't really an issue, but something like a Suggestion. Thanks anyway!

**Comment by FPtje** [comment]
It's possible by creating FPP groups and assigning people to them. Make one group per player. I've decided that I'm not going to add a millionth way to restrict tools in FPP.
