### ISSUE TITLE
Toolgun restricted! incorrect group!

### ISSUE THREAD

**Issue by amirsh34** [FPtje/Falcos-Prop-protection#166]
Recently i had a problem with my server which no tool worked.
Ive played a little with the ffp menu and now only some dont work.
in addition to that no tool work on the world.
some time the tool says "Toolgun restricted! incorrect group!" and sometime it just doesn't work.
(I got an ulx rank of owner)
is there a way to fix it? and if not Is there a way to reset the falco settings

**Comment by FPtje** [comment]
Not a valid bug report

**Comment by amirsh34** [comment]
but i posted it in issues not bug report

**Comment by FPtje** [comment]
Github issues are only for things that are my responsibility. Specifically: bugs and suggestions.
