### ISSUE TITLE
FPP Permissions to ULX Groups

### ISSUE THREAD

**Issue by Noah8282** [FPtje/Falcos-Prop-protection#167]
So FPP (Falco's Prop Protection) is a mod that makes you able to do all kinds of different stuff. One of these very important admin settings are, that admins can pull in other peoples cars and props and so on. The problem is when i add myself to the default superadmin group in ULX i can pull in other peoples props/vehicles. But when i create a custom group that inherits from superadmin, the people in the group still can't pull in other peoples props.

Hope some of you guys can help :)

- Noah

**Comment by FPtje** [comment]
Not a help forum
