### ISSUE TITLE
Admins cannot interact with players props

### ISSUE THREAD

**Issue by SmzKosTek** [FPtje/Falcos-Prop-protection#168]
I recently installed darkrp on my server and first major issue occurred. Admins cannot interact with any props even when its set that Admins can interact with any props.
Admins are only allowed to interact with their own props and also World props. However, world props are on RED (Cannot interact).

**Comment by FPtje** [comment]
Give the Admin usergroups CAMI access to touching other players' props in your installed Admin mods.
