### ISSUE TITLE
Timer Failed!

### ISSUE THREAD

**Issue by SligWolf** [FPtje/Falcos-Prop-protection#169]
Hiho!
I had this error 2 times:

![error_lua_fpp](https://cloud.githubusercontent.com/assets/17761396/13666262/e494d41a-e6b0-11e5-9409-6c4f6b4be259.png)

It is the first time I report here, so I hope this is ok like I did it. 
If you need some more infos, i will try to help. ^^

**Comment by FPtje** [comment]
DarkRP will be updated later
