### ISSUE TITLE
SetSolid and FPP

### ISSUE THREAD

**Issue by SligWolf** [FPtje/Falcos-Prop-protection#170]
I'm quite not sure if this is a error from fpp, so if I make a mistake here, then I'm sorry.
I can't explain the issue in words but i made a short video.

These addons were enabled in the test:
- Falco's Prop Protection (FPP) (Workshop / Newest)
- Wire (SVN)

NOTE:
- I used standard jeeps to show what happen.
- Green oildrum = SetSolid with a timer
- Red oildrum = SetSolid without a timer
- Remove / Unweld the blue barrel

Video: [https://www.youtube.com/watch?v=zD-3bS4fIB4&feature=youtu.be](url)

If you want to test it on your own, here is a link to the test script I made (Lua):
- You do not need any other addons, only FPP.

Pastebin: [http://pastebin.com/PaM8gZLv](url)

**Comment by FPtje** [comment]
Huh, reactions.
Anyway, nice work on making a script to reproduce the issue. I presume the problem always arises with `SOLID_NONE` as parameter for `SetSolid`?

**Comment by SligWolf** [comment]
Hiho!
I did some tests after i saw your post and can say to 100%:  
Yes, only with `SOLID_NONE`

**Comment by FPtje** [comment]
You should install glualint by the way. It's going mental over the trailing whitespaces and inconsistent use of tabs and spaces for indentation.
