### ISSUE TITLE
Unfreeze all Physgun problem

### ISSUE THREAD

**Issue by JustinCase11223** [FPtje/Falcos-Prop-protection#172]
On my server Unfreeze all with the physgun doesn't seem to be protected, I've currently got these settings in Physgun Options.

unfreeze all (double tapping R with physgun)

Physgun protection enabled *ticked*
Admins can physgun all entities *ticked*
People can physgun world entities *unticked*
Admin can physgun world entities *ticked*
People can physgun blocked entities *unticked*
Admin can physgun blocked entities *unticked*
Physgun reload protection enabled *ticked*

**Comment by FPtje** [comment]
How is this a problem?

**Comment by JustinCase11223** [comment]
Well cause guests can unfreeze admins props and thats not to good

**Comment by FPtje** [comment]
"Unfreeze all" Unfreezes your own props, how would you unfreeze an admin's props?

**Comment by JustinCase11223** [comment]
I'm not sure why they are able to to it but randomly everyones props on the server will just unfreeze removing all constraints .-.

**Comment by FPtje** [comment]
Removing all constraints? That doesn't sound like something double tapping R with physgun is supposed to do at all. Unless you have some weird addon that thinks this is a neat feature, this is not a physgun double tap R thing.

**Comment by Extra-Mental** [comment]
He was miss informed. The props don't un-constrain themselves, he just saw it happen to people with no building with no prop constraints, but anyone that has the ability to touch all props, if they double tap R on the world; every prop that is constrained to the world (such as no colide or ropes) drops to the ground regardless of who owns it.

**Comment by FPtje** [comment]
Surely when props constrained to the world suddenly fall to the ground, their constraints with the world must be removed? Otherwise the constraints would keep the props up.

**Comment by Extra-Mental** [comment]
It doesn't remove the constraint, props welded to the world still stay but they still unfreeze when the unfreeze all occurs on the world, but loose constraints like no-colides will make them drop.

**Comment by FPtje** [comment]
you mean wiggle a bit or what?

**Comment by FPtje** [comment]
Also, let me show you what I mean.
Player A has three props, a bar, a locker and a box:
![2016-03-16_13-19-13](https://cloud.githubusercontent.com/assets/1202014/13812025/d0edec30-eb79-11e5-850e-8c365c35f66e.jpg)

The bar is welded to the world, the locker is no-collided with the bar (can't just no collide to world, you need a separate tool for that), and the box is just frozen.

Player B has a melon frozen in mid air and double taps R on the world. This happens:
![2016-03-16_13-19-22](https://cloud.githubusercontent.com/assets/1202014/13812043/f1445faa-eb79-11e5-8eaf-03521bde3290.jpg)

The melon, Player B's own prop, drops to the floor. **ALL** Player A's props remain in air, all frozen. The bar remains welded to the world and the locker remains no-collided to the bar.

**Comment by Extra-Mental** [comment]
If Player B has a higher rank over Player A in an admin mod such as evolve and is able to touch everyones entites, all of Player A's props will unfreeze if they are constrained to the world in any way.

People on the server are using no-colide multi which automatically no colides to world entites which I think is linking them to the world.

**Comment by FPtje** [comment]
Player B was the owner of the server. Player A had no access.

**Comment by Extra-Mental** [comment]
Lower ranks that cannot touch all players entities cannot do it, they can only do it to their own.

**Comment by FPtje** [comment]
Also, you seem to be confusing single tap R and double tap R with physgun.

Single tap R: unfreezes the prop your looking at and every prop constrained to it. 
Double tap R: unfreezes all of your OWN props, regardless of constraints.

Even then, single tap R doesn't do anything when you're looking at the world, *even* when there is shit constrained to the world.

**Comment by Extra-Mental** [comment]
I haven't said anything about single tapping of R, I've been talking about double tapping R on the world.

**Comment by FPtje** [comment]
Double tapping R on the world doesn't do anything with constraints.

**Comment by Extra-Mental** [comment]
If you double tap R on an entity, itself and anything constrained to it will unfreeze.

**Comment by Extra-Mental** [comment]
The same happens to the world

**Comment by FPtje** [comment]
You're the one making this ridiculous fucking claim, you should be the one proving it, but let me be fucking kind and prove you the fuck wrong.

This function is the one called on physgun double tap:
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/base/gamemode/obj_player_extend.lua#L98
`meta:UnfreezePhysicsObjects()`

It iterates over the player's member variable `FrozenPhysicsObjects` and unfreezes everything it finds.

There is NO mention of constraints. `FrozenPhysicsObjects` in GMod is only populated by your **own** entities. I **repeat**. Double tap R does **NOTHING** with constraints.

Now about single tap. Single tap is the **ONLY** physgun action that does **anything** with constraints. The function for that is defined right above the double tap one:
https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/base/gamemode/obj_player_extend.lua#L53
`meta:PhysgunUnfreeze( weapon )`

Line 69, states that **NOTHING** is to be done when you're looking at the world and just single tapping R.


Let me fucking summarize: 

# DOUBLE TAP R DOESN'T DO ANYTHING WITH CONSTRAINTS

**Comment by Extra-Mental** [comment]
You are right, that code does have nothing to do with constrained entities, we must have a conflicting addon, sorry for wasting your time.
