### ISSUE TITLE
How do i use fpp_cleanup

### ISSUE THREAD

**Issue by SilentDeathTheSeal** [FPtje/Falcos-Prop-protection#174]
I tried using fpp_cleanup someonesplayername and when I enter it says "invalid player" and I am spelling it correctly

**Comment by FPtje** [comment]
use the FPP menu in Q

**Comment by SilentDeathTheSeal** [comment]
i know that i can use that but i want to use the console command

**Comment by FPtje** [comment]
`fpp_cleanup disconnected`

or 
`fpp_cleanup userid`

where userid is a player's UserID, retrieved by entering status in console and looking at the numbers players have in front of their names.

**Comment by SilentDeathTheSeal** [comment]
also, how would I remove everyone's props with the command
(sorry for making a new issue I thought after you closed the issue you wouldn't get notified)

**Comment by Bo98** [comment]
If you want to remove everyone's props you can just use GMod's default cleanup command for that:

```
gmod_admin_cleanup props
```

**Comment by SilentDeathTheSeal** [comment]
ah thanks

**Comment by SilentDeathTheSeal** [comment]
well that cleans up props
but what about everything else

**Comment by Bo98** [comment]
Omit the props part if you want to cleanup everything:

```
gmod_admin_cleanup
```

**Comment by SilentDeathTheSeal** [comment]
ok thanks
