### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/Falcos-Prop-protection#176]
[ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/server/core.lua:471: attempt to index local 'trace' (a nil value)
  1. CanTool - gamemodes/darkrp/gamemode/modules/fpp/pp/server/core.lua:471
   2. CPPICanTool - gamemodes/darkrp/gamemode/modules/fpp/pp/sh_cppi.lua:66
    3. Call - gamemodes/darkrp/gamemode/modules/base/sv_gamemode_functions.lua:368
     4. Filter - lua/autorun/properties/bodygroups.lua:12
      5. Receive - lua/autorun/properties/bodygroups.lua:112
       6. func - lua/includes/modules/properties.lua:137
        7. unknown - lua/includes/extensions/net.lua:32

**Comment by FPtje** [comment]
Your properties/bodygroups.lua is requesting CanProperty of a non-Entity.
