### ISSUE TITLE
FPP Keeps resetting after every single bullshit restart..

### ISSUE THREAD

**Issue by NLGBrian** [FPtje/Falcos-Prop-protection#179]
well i resetted FPP by using a command i found on here, but after a few days it keeps resetting my fpp >.<  how to fix

**Comment by FPtje** [comment]
Time doesn't reset settings. Those "two days" are most likely to be some other admin changing the settings back.

**Comment by NLGBrian** [comment]
Who actually can set the settings from what rank ?

**Comment by FPtje** [comment]
There's a CAMI privilege for that.

**Comment by FPtje** [comment]
superadmin by default

**Comment by NLGBrian** [comment]
Nobody is actually granted access to, i didnt change anything. but the fpp all stuff keeps restoring to default settings ;l

**Comment by FPtje** [comment]
I can not reproduce it. It'll be your responsibility to figure out the cause. For all I know you use MySQL and it can't connect.

**Comment by NLGBrian** [comment]
So if i uninstall MySQL it will be fixed?

**Comment by FPtje** [comment]
I don't know
