### ISSUE TITLE
MySQL Problem

### ISSUE THREAD

**Issue by InfamousYT** [FPtje/Falcos-Prop-protection#181]
Hello! I've setup MySQL on my Falco's Prop Protection but this is the error in console I get:

`addons/falcos-prop-protection-master/lua/libraries/mysqlite/mysqlite.lua:334: attempt to index upvalue 'GAMEMODE' (a nil value)`

Thank you.

**Comment by FPtje** [comment]
There must be an earlier error in your gamemode that causes this error.

`GAMEMODE` cannot be nil.

**Comment by InfamousYT** [comment]
So how can I fix this?

**Comment by FPtje** [comment]
> There must be an earlier error in your gamemode that causes this error.

Fix whatever the earlier error is and you'll fix this one along with it.

**Comment by InfamousYT** [comment]
It's a fresh install of Sandbox.

**Comment by FPtje** [comment]
That's great

**Comment by InfamousYT** [comment]
So I don't know what could be wrong with it. (Sorry if I'm bad at this)

**Comment by FPtje** [comment]
I can't help you.
