### ISSUE TITLE
Gmod Crash to desktop [Solved]

### ISSUE THREAD

**Issue by killerrichard** [FPtje/Falcos-Prop-protection#186]
Hello,

When open the blocked model list in spawn menu.
Gmod crash with the error modal box : "Bad inline model number 175" 

and this is my database model fpp.

All my model database are belongs to you.. lol

Thanks your for you awesome help :+1: 

"models/cranes/crane_frame.mdl"
"models/items/item_item_crate.mdl"
"models/props/cs_militia/silo_01.mdl"
"models/props/cs_office/microwave.mdl"
"models/props/de_train/biohazardtank.mdl"
"models/props_buildings/building_002a.mdl"
"models/props_buildings/collapsedbuilding01a.mdl"
"models/props_buildings/project_building01.mdl"
"models/props_c17/consolebox01a.mdl"
"models/props_c17/oildrum001_explosive.mdl"
"models/props_c17/paper01.mdl"
"models/props_c17/trappropeller_engine.mdl"
"models/props_canal/canal_bridge01.mdl"
"models/props_canal/canal_bridge02.mdl"
"models/props_canal/canal_bridge03a.mdl"
"models/props_canal/canal_bridge03b.mdl"
"models/props_combine/combine_citadel001.mdl"
"models/props_combine/combine_mine01.mdl"
"models/props_combine/combinetrain01.mdl"
"models/props_combine/combinetrain02a.mdl"
"models/props_combine/combinetrain02b.mdl"
"models/props_combine/prison01.mdl"
"models/props_combine/prison01c.mdl"
"models/props_industrial/bridge.mdl"
"models/props_junk/garbage_takeoutcarton001a.mdl"
"models/props_junk/gascan001a.mdl"
"models/props_junk/glassjug01.mdl"
"models/props_junk/trashdumpster02.mdl"
"models/props_phx/amraam.mdl"
"models/props_phx/ball.mdl"
"models/props_phx/cannonball.mdl"
"models/props_phx/huge/evildisc_corp.mdl"
"models/props_phx/misc/flakshell_big.mdl"
"models/props_phx/misc/potato_launcher_explosive.mdl"
"models/props_phx/mk-82.mdl"
"models/props_phx/oildrum001_explosive.mdl"
"models/props_phx/torpedo.mdl"
"models/props_phx/ww2bomb.mdl"
"models/props_wasteland/cargo_container01.mdl"
"models/props_wasteland/cargo_container01b.mdl"
"models/props_wasteland/cargo_container01c.mdl"
"models/props_wasteland/depot.mdl"
"models/xqm/coastertrack/special_full_corkscrew_left_4.mdl"
"models/props_c17/consolebox05a.mdl"
"models/props_c17/consolebox03a.mdl"
"models/items/car_battery01.mdl"
"models/props_lab/reciever01a.mdl"
"models/weapons/w_bugbait.mdl"
"models/props/cs_militia/footlocker01_open.mdl"
"models/props_c17/column02a.mdl"
"models/props_c17/trappropeller_blade.mdl"
"models/props_citizen_tech/windmill_blade002a.mdl"
"models/props_citizen_tech/windmill_blade004a.mdl"
"models/arc/atm_cardmachine.mdl"
"models/nv_weed_plant/plant_medium.mdl"
"models/arc/atm.mdl"
"models/thedoctor/crackmachine_off.mdl"
"models/thedoctor/crackmachine_on.mdl"
"models/failure/mk6/mk6.mdl"
"models/bitminer/bitminerheavy.mdl"
"models/bitminer/bitminerlight.mdl"
"models/bitminer/bitminermedium.mdl"
"models/attachments/cmore.mdl"
"models/attachments/kascope.mdl"
"models/bunneh/scope01.mdl"
"models/wystan/cmag.mdl"
"models/fishy/furniture/piano_seat.mdl"
"models/teh_maestro/popcorn.mdl"
"models/props_junk/propane_tank001a.mdl"
"models/props_junk/propanecanister001a.mdl"
"models/props/de_nuke/storagetank.mdl"
"models/props/de_nuke/nuclearfuelcontainer.mdl"
"models/props/de_nuke/pipesa_bombsite.mdl"
"models/props/de_nuke/coolingtower.mdl"
"models/props/de_nuke/coolingtank.mdl"
"models/props/cs_militia/rockpileramp01.mdl"
"models/props/cs_assault/money.mdl"
"models/props_wasteland/coolingtank02.mdl"
"models/props_wasteland/rockcliff_cluster02c.mdl"
"models/props_wasteland/rockcliff_cluster02a.mdl"
"models/props_wasteland/rockcliff_cluster03a.mdl"
"models/props_wasteland/rockcliff_cluster03c.mdl"
"models/hunter/blocks/cube8x8x8.mdl"
"models/hunter/tubes/tube2x2x16d.mdl"
"models/hunter/tubes/tube4x4x16d.mdl"
"models/hunter/tubes/tube4x4x16c.mdl"
"models/mechanics/wheels/wheel_spike_48.mdl"
"models/mechanics/wheels/wheel_spike_24.mdl"
"models/xqm/coastertrack/turn_slope_down_90_4.mdl"
"models/xqm/coastertrack/turn_slope_down_90_3.mdl"
"models/props/de_port/tankoil02.mdl"
"models/props/de_port/tankoil01.mdl"
"models/props/de_port/cargo_container01.mdl"
"models/balloons/hot_airballoon.mdl"
"models/xqm/jetbody3_s2.mdl"
"models/xqm/jetbody3_s3.mdl"
"models/nova/jalopy_seat.mdl"
"models/props_phx/huge/tower.mdl"
"models/props_phx/huge/road_long.mdl"
"models/props_phx/huge/road_medium.mdl"
"models/props_phx/huge/road_short.mdl"
"models/props_phx/huge/road_curve.mdl"
"models/xqm/coastertrack/special_half_corkscrew_right_4.mdl"
"models/xqm/coastertrack/special_half_corkscrew_right_3.mdl"
"models/xqm/coastertrack/slope_225_down_1.mdl"
"models/xqm/coastertrack/slope_225_down_2.mdl"
"models/xqm/coastertrack/slope_225_down_3.mdl"
"models/xqm/coastertrack/special_full_corkscrew_right_4.mdl"
"models/xqm/coastertrack/special_full_corkscrew_right_3.mdl"
"models/xqm/coastertrack/special_full_loop_4.mdl"
"models/xqm/coastertrack/turn_180_1.mdl"
"models/xqm/coastertrack/bank_turn_180_1.mdl"
"models/combine_helicopter/helicopter_bomb01.mdl"
"models//cheeze/wires/ram.mdl"
"models/cheeze/wires/ram.mdl"
"models/kobilica/value.mdl"
"models//cheeze/wires/cpu.mdl"
"models/cheeze/wires/cpu.mdl"
"models//cheeze/wires/mini_cpu.mdl"
"models/cheeze/wires/mini_cpu.mdl"
"models/bull/gates/transistor1.mdl"
"models/bull/gates/resistor.mdl"
"models/props_lab/huladoll.mdl"
"models/props_interiors/pot01a.mdl"
"models/items/ammocrates/cratenervegas.mdl"
"models/items/ammocrates/cratefrags.mdl"
"models/items/ammocrates/cratestickys.mdl"
"models/items/ammocrates/crateprox.mdl"
"models/items/ammocrates/crateieds.mdl"
"models/items/ammocrates/cratec4.mdl"
"models/items/battery.mdl"
"models/healthvial.mdl"
"models/weapons/w_missile_closed.mdl"
"*175"
"models/hunter/tubes/tube4x4x16.mdl"
"models/hunter/tubes/tube4x4x6b.mdl"
"models/hunter/tubes/tube4x4x8.mdl"
"models/hunter/blocks/cube6x6x6.mdl"
"models/hunter/blocks/cube4x4x4.mdl"
"models/combine_apc.mdl"
"models/props_combine/combine_train02a.mdl"
"models/combine_dropship.mdl"
"models/combine_helicopter.mdl"
"models/props_trainstation/train003.mdl"
"models/props_trainstation/train002.mdl"
"models/props_trainstation/train001.mdl"
"models/props_combine/combinetrain01a.mdl"
"models/props_combine/combine_train02b.mdl"
"models/props_vehicles/car004b_physics.mdl"
"models/props_vehicles/car005a_physics.mdl"
"models/props_vehicles/car005b_physics.mdl"
"models/props_vehicles/car004a_physics.mdl"
"models/props_vehicles/tanker001a.mdl"
"models/props_vehicles/car001b_hatchback.mdl"
"models/props_vehicles/car001b_phy.mdl"
"models/props_vehicles/car002a_physics.mdl"
"models/props_canal/boat001b.mdl"
"models/props_canal/boat002b.mdl"
"models/airboat.mdl"
"models/buggy.mdl"
"models/props_vehicles/car003b_physics.mdl"
"models/props_trainstation/train005.mdl"
"models/props_vehicles/car003a_physics.mdl"
"models/props_vehicles/apc001.mdl"
"models/props_vehicles/wagon001a_phy.mdl"
"models/props_vehicles/car002b_physics.mdl"
"models/props_vehicles/van001a_physics.mdl"
"models/props_vehicles/truck001a.mdl"
"models/props_vehicles/car001a_hatchback.mdl"
"models/props_vehicles/car001a_phy.mdl"
"models/props_canal/boat001a.mdl"
"models/props_vehicles/trailer002a.mdl"
"models/hunter/blocks/cube8x8x4.mdl"
"models/hunter/blocks/cube4x6x4.mdl"
"models/hunter/blocks/cube8x8x2.mdl"
"models/hunter/blocks/cube6x8x2.mdl"
"models/hunter/blocks/cube6x6x2.mdl"
"models/hunter/blocks/cube8x8x1.mdl"
"models/props_combine/weaponstripper.mdl"
"models/props_wasteland/cranemagnet01a.mdl"
"models/props/de_nuke/car_nuke.mdl"
"models/props/de_nuke/car_nuke_black.mdl"
"models/props/de_nuke/car_nuke_glass.mdl"
"models/props/de_nuke/car_nuke_red.mdl"
"models/props_vehicles/trailer001a.mdl"
"models/props_mining/rock004.mdl"
"models/props_swamp/cliff_wall_01.mdl"
"models/props_forest/rock002.mdl"
"models/props_forest/rock001.mdl"
"models/hunter/plates/plate8x8.mdl"
"models/props_wasteland/rockcliff05a.mdl"
"models/props_wasteland/rockcliff05e.mdl"
"models/props_wasteland/rockcliff05f.mdl"
"models/props_wasteland/rockcliff05b.mdl"
"models/props_wasteland/rockcliff_cluster02b.mdl"
"models/props_wasteland/rockcliff_cluster01b.mdl"
"models/props_wasteland/rockcliff_cluster03b.mdl"
"models/props_wasteland/buoy01.mdl"
"models/props_foliage/rock_coast02g.mdl"
"models/props_foliage/rock_coast02h.mdl"
"models/props_foliage/rock_coast02a.mdl"
"models/props_foliage/rock_coast02b.mdl"
"models/props_foliage/rock_coast02d.mdl"
"models/props_foliage/rock_coast02e.mdl"
"models/props_foliage/rock_coast02f.mdl"
"models/props_rooftop/parliament_dome_destroyed_interior.mdl"
"models/props_rooftop/rooftop_set01b.mdl"
"models/props/de_train/tanker.mdl"
"models/props/cs_militia/van.mdl"
"models\props/cs_militia/van.mdl"
"models/hunter/plates/plate16x16.mdl"
"models/props_phx/trains/tracks/track_16x.mdl"
"models/props_phx/trains/tracks/track_turn90.mdl"
"models/props_phx/trains/tracks/track_8x.mdl"
"models/props_phx/trains/tracks/track_switch2.mdl"
"models/props_phx/trains/tracks/track_turn45.mdl"
"models/props_phx/trains/tracks/track_x.mdl"
"models/xqm/jetbody2big.mdl"
"models/hunter/plates/plate8x16.mdl"
"models/hunter/misc/shell2x2a.mdl"
"models/props_phx/construct/wood/wood_dome360.mdl"
"models/props_phx/construct/metal_dome360.mdl"
"models/props_phx/construct/windows/window_dome360.mdl"
"models/hunter/misc/shell2x2b.mdl"
"models/props_phx/construct/glass/glass_dome360.mdl"
"models/hunter/tubes/tube2x2x8.mdl"
"models/hunter/tubes/tube2x2x+.mdl"
"models/hunter/tubes/tubebend2x2x90square.mdl"
"models/hunter/tubes/tubebend2x2x90.mdl"
"models/hunter/tubes/tube2x2xt.mdl"
"models/hunter/tubes/tube2x2xta.mdl"
"models/hunter/tubes/tube2x2xtb.mdl"
"models/hunter/tubes/tube4x4x1to2x2.mdl"
"models/hunter/tubes/tube4x4x2.mdl"
"models/hunter/tubes/tube4x4x4.mdl"
"models/hunter/tubes/tube4x4x6.mdl"
"models/hunter/tubes/tube4x4x5.mdl"
"models/hunter/tubes/tube4x4x3b.mdl"
"models/hunter/tubes/tube4x4x5b.mdl"
"models/hunter/tubes/tube4x4x4b.mdl"
"models/hunter/tubes/tube4x4x4c.mdl"
"models/hunter/tubes/tube4x4x3c.mdl"
"models/hunter/tubes/tube4x4x3.mdl"
"models/hunter/tubes/tube4x4x2b.mdl"
"models/xqm/cylinderx1large.mdl"
"models/mechanics/wheels/tractor.mdl"
"models/xeon133/racewheelskinny/race-wheel-80_s.mdl"
"models/mechanics/wheels/wheel_smooth_96.mdl"
"models/mechanics/wheels/wheel_smooth_72w.mdl"
"models/props_phx/wheels/monster_truck.mdl"
"models/xeon133/offroad/off-road-80.mdl"
"models/xqm/airplanewheel1large.mdl"
"models/mechanics/wheels/wheel_rounded_72.mdl"
"models/props_vehicles/truck003a.mdl"
"models/gantry_crane/crane_beam.mdl"
"models/hunter/plates/plate8x24.mdl"
"models/hunter/plates/plate6x16.mdl"
"models/props_c17/playground_swingset_seat01a.mdl"
"models/props_phx/trains/fsd-overrun2.mdl"
"models/props_phx/trains/track_4096.mdl"
"models/props_phx/trains/monorail4.mdl"
"models/props_phx/trains/track_2048.mdl"
"models/props_phx/trains/track_1024.mdl"
"models/props_phx/trains/monorail3.mdl"
"models/props_phx/trains/monorail1.mdl"
"models/props_phx/trains/tracks/track_switcher.mdl"
"models/props_phx/trains/tracks/track_4x.mdl"
"models/props/de_nuke/warehouse1d.mdl"
"models/props/de_nuke/warehouse1b.mdl"
"models/props/de_nuke/ibeams_warehouseroof.mdl"
"models/props/de_nuke/nuklogo.mdl"
"models/props/de_nuke/powerwires.mdl"
"models/props/de_nuke/turbinegenerator.mdl"
"models/props/de_nuke/catwalk_support_b.mdl"
"models/props/de_nuke/catwalk_support_a.mdl"
"models/props/de_nuke/electricalbox01.mdl"
"models/props/de_train/flatcar.mdl"
"models/props/de_train/diesel.mdl"
"models/props/de_train/boxcar2.mdl"
"models/props/de_train/boxcar.mdl"
"models/props/de_train/de_train_ibeams_02.mdl"
"models/props_industrial/light.mdl"
"models/props_industrial/oil_pipes.mdl"
"models/props_pipes/gutter_320_001a.mdl"
"models/combine_room/combine_monitor003a.mdl"
"models/props_phx/cannon.mdl"
"models/props_phx/rocket1.mdl"
"models/props_combine/combine_window001.mdl"
"models/props/vegsubstoreprops.mdl"
"models/props/pdpillars.mdl"
"models/props/beachhouse1windowset1.mdl"
"models/props/beachhouse1windowset2.mdl"
"models/props/pdglasswall.mdl"
"models/props/pdgaragestairs.mdl"
"models/props/vegsuburbsbuildingprops.mdl"
"models/props/cornerbuildingprops.mdl"
"models/props/richdistrictbuildingprops.mdl"
"models/cranes/crane_frame_interior.mdl"
"models/props_buildings/collapsedbuilding02b.mdl"
"models/props_buildings/row_res_1_fullscale.mdl"
"models/props_buildings/row_church_fullscale.mdl"
"models/props_buildings/collapsedbuilding02a.mdl"
"models/props_c17/furnituremattress001a.mdl"
"models/mechanics/gears/gear24x24_large.mdl"

**Comment by killerrichard** [comment]
Problem solved 

Line : "*175"

**Comment by FPtje** [comment]
Adding "*175" or "175" to the blocked models list before opening the UI doesn't crash anything for me.
