### ISSUE TITLE
Lua Error Spam due to Wiremod

### ISSUE THREAD

**Issue by Hazbelll** [FPtje/Falcos-Prop-protection#187]
```
[04:03] gamemodes/darkrp/gamemode/modules/fpp/pp/server/core.lua:402: Tried to use a NULL entity!
  1. SteamID - [C]:-1
   2. fn - gamemodes/darkrp/gamemode/modules/fpp/pp/server/core.lua:402
    3. Call - lua/ulib/shared/hook.lua:110
     4. output - lua/wire/gates/entity.lua:793
      5. CalcOutput - lua/entities/gmod_wire_gate.lua:112
       6. unknown - lua/entities/gmod_wire_gate.lua:94
```
The above error is being spammed into Server Console non-stop. Unfortunately I don't know exactly what's caused it as I was tabbed out of the game before it happened. It ceased a short while after I tabbed back in.

**Comment by roboderpy** [comment]
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L400
FPP.Protect.CanTool() getting called with invalid entity.
This is wiremod bug.

**Comment by FPtje** [comment]
Yeah, don't call a hook that requires a player as argument without giving a valid player as argument.
