### ISSUE TITLE
[DarkRP] SetOwner Issue with FPP and F4 Spawned Sents

### ISSUE THREAD

**Issue by Noname12345GER** [FPtje/Falcos-Prop-protection#188]
Hello Falco,

I already tried finding an answer for my problem so i tried the things with were provided here with no succsess;
http://forum.darkrp.com/threads/setting-the-fpp-owner.76/
(We are using DarkRP_2.6.3)

For a custom Doantor job is it required that this TARDIS spawned via F4 menu is assigned in FPP to the "buyer/spawner"

So this is the TARDIS addon;
https://github.com/MattJeanes/TARDIS/tree/legacy

Here is the path for the init.lua and the shared.lua;
https://github.com/MattJeanes/TARDIS/tree/legacy/lua/entities/sent_tardis

Basically i have no clue what i could do elsehow (really i dont), because if its not possible to make the TARDIS a non-world entity, then it would break some important key feataures (Such as Sonic Screwdriver Linking, and the Isomorph in the TARDIS itselve, if you are familiar with it.) 

I would like to know where the code belongs in exactly because im not that experienced with LUA. 
(Sure you might ask why am i running an DarkRP server then? Well, the owner said if i want that Custom job i shall fix it myselve :/ )

I know you are busy, but i hope you would try to assist me.

Best regards, Noname12345GER

**Comment by roboderpy** [comment]
Use playerBoughtCustomEntity and ent:CPPISetOwner()

**Comment by Noname12345GER** [comment]
> Use playerBoughtCustomEntity and ent:CPPISetOwner()

Could you please be more precise?
