### ISSUE TITLE
Admins cannot touch others' props/entities

### ISSUE THREAD

**Issue by Bryantdl7** [FPtje/Falcos-Prop-protection#190]
In the screenshot taken, I am the rank superadmin for ULX. 
![image](https://cloud.githubusercontent.com/assets/5564661/17525787/547bc254-5e32-11e6-8a41-22438468b44c.png)

As you can see, I am unable to touch other people's props. I have been using FPP for around two years now, and am thinking this might be a bug in a recent update. Just to be sure that it was not something on client side, I have had multiple people with the same level of power as me try and grab things aswell. Not only that, I have also checked to make sure that it isn't a user-defined setting. 
![image](https://cloud.githubusercontent.com/assets/5564661/17525849/9964a692-5e32-11e6-9274-e87df5360a6d.png)

One thing I found while looking through my clientside_errors.txt was these errors. 
[ERROR] workshop/lua/fpp/client/ownability.lua:43: Tried to use a NULL entity!
  1. __newindex - [C]:-1
   2. entGetOwner - workshop/lua/fpp/client/ownability.lua:43
    3. CPPIGetOwner - workshop/lua/fpp/sh_cppi.lua:36

[ERROR] workshop/lua/fpp/client/ownability.lua:43: Tried to use a NULL entity!
  1. __newindex - [C]:-1
   2. entGetOwner - workshop/lua/fpp/client/ownability.lua:43
    3. CPPIGetOwner - workshop/lua/fpp/sh_cppi.lua:36
     4. check_owner - workshop/lua/pac3/core/client/owner_name.lua:23
      5. HandleOwnerName - workshop/lua/pac3/core/client/owner_name.lua:123
       6. CheckOwner - workshop/lua/pac3/core/client/base_part.lua:239
        7. unknown - workshop/lua/pac3/core/client/parts/group.lua:19

I noticed that pac3 is being mentioned in this second error. Should I take this issue to them as well? I plan on opening a ticket with their github page aswell and linking them to this.

Thanks in advance!

**Comment by Bo98** [comment]
Do you have any serverside errors (lua_errors_server.txt)?

**Comment by Bryantdl7** [comment]
Thats located in garrysmod right? if so, then no.

**Comment by Bo98** [comment]
The clientside errors are indeed PAC's issue. Though it shouldn't have any affect on your issue since physgun protection is enforced serverside.

Check that the "Admins can physgun all entities" option is checked under "Physgun options" in the admin settings of FPP.

**Comment by Bryantdl7** [comment]
Hi, I have tried that. I have also done a clean install of the addon. And disallowing admins then allowing them that ability.

**Comment by FPtje** [comment]
PEBCAK
