### ISSUE TITLE
FPP Resets everytime I start/restart my server.

### ISSUE THREAD

**Issue by extern56** [FPtje/Falcos-Prop-protection#191]
FPP Resets every time I start/restart my server. I have to add all blacklisted tools,props,entities again and again, and change the permissions again and again.

My server: 192.99.200.148:27065
My steam: https://steamcommunity.com/id/externalthunder/

**Comment by FPtje** [comment]
Cannot reproduce

**Comment by sebastianmonroe42** [comment]
I also have this. Nothing changed just magically happen. I can see the blacklisted props if I used the msql found in the fpp. Nothing shows in the blacklist ig though.
