### ISSUE TITLE
lua error in console when loading server

### ISSUE THREAD

**Issue by Gamerpro2266** [FPtje/Falcos-Prop-protection#192]
hi i got a lua error in my console on start up 

[ERROR] lua/fpp/server/settings.lua:521: attempt to index field 'Access' (a nil value)
  1. fn - lua/fpp/server/settings.lua:521
   2. unknown - addons/ulib-master/lua/ulib/shared/hook.lua:109

iam using workshop

**Comment by FPtje** [comment]
You fucked up your installation of DarkRP. Please go to forum.darkrp.com

**Comment by FPtje** [comment]
Hi, I don't. Please go to Forum.darkrp.com
