### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Gamerpro2266** [FPtje/Falcos-Prop-protection#193]
[Falco's Prop Protection (FPP)] Unauthed player
  1. query - [C]:-1
   2. fn - addons/ulib-master/lua/ulib/shared/cami_ulib.lua:18
    3. Call - addons/ulib-master/lua/ulib/shared/hook.lua:109
     4. PlayerHasAccess - lua/libraries/sh_cami.lua:370
      5. GetPlayersWithAccess - addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:103
       6. Refresh - addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:111
        7. unknown - addons/ultimatelogs/lua/ultimatelogs/shared/sh_ultimatelogs.lua:124

**Comment by FPtje** [comment]
ULib problem.

**Comment by FPtje** [comment]
That or ultimatelogs.

**Comment by Gamerpro2266** [comment]
also you know the thing when you talk ingame and it tells you whos near you and listening can you remove that or is that fixed

**Comment by FPtje** [comment]
that's not a thing FPP does.

**Comment by FPtje** [comment]
also I don't just remove things in DarkRP.

**Comment by Gamerpro2266** [comment]
also whats better using workshop or the one that comes with darkrp

**Comment by FPtje** [comment]
You don't need two installations of FPP. The FPP that ships with DarkRP is exactly the same as the addon version.

**Comment by Gamerpro2266** [comment]
ok thanks for your help today
