### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by Gamerpro2266** [FPtje/Falcos-Prop-protection#194]
[ERROR] gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:211: attempt to call global 'Label' (a userdata value)
  1. func - gamemodes/darkrp/gamemode/modules/fpp/pp/client/menu.lua:211
   2. FillViaFunction - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:100
    3. FillViaTable - gamemodes/sandbox/gamemode/spawnmenu/controlpanel.lua:89
     4. ActivateTool - lua/includes/modules/spawnmenu.lua:291
      5. DoClick - gamemodes/sandbox/gamemode/spawnmenu/toolpanel.lua:82
       6. unknown - lua/vgui/dlabel.lua:218

**Comment by FPtje** [comment]
Conflicting addon
