### ISSUE TITLE
Remove a model with command?

### ISSUE THREAD

**Issue by Xean00796** [FPtje/Falcos-Prop-protection#195]
I have perma lawboard but it says it block so i want to remove the model name "perma_laws" can i do this with a command

**Comment by L33TBEANS** [comment]
What you specified is the entity name and not the model name. To get the model name you will have to find out what model the entity is using, a lot of law boards use this model: models/props/cs_assault/billboard.mdl

fpp_removeblockedmodel "<the model the lawboard uses>"

**Comment by Xean00796** [comment]
Thank you it worked Thanks you
