### ISSUE TITLE
serverside errors

### ISSUE THREAD

**Issue by sw2719** [FPtje/Falcos-Prop-protection#196]
[ERROR] lua/includes/util.lua:181: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:181
   2. calculateCanTouchForType - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:113
    3. calculateCanTouch - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:169
     4. recalculateCanTouch - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:209
      5. unknown - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:493

Timer Failed! [Simple][@addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua (line 492)]

[ERROR] lua/includes/util.lua:181: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:181
   2. calculateCanTouchForType - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:113
    3. calculateCanTouch - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:169
     4. recalculateCanTouch - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:209
      5. unknown - addons/falcos-prop-protection-master/lua/fpp/server/core.lua:660

Timer Failed! [Simple][@addons/falcos-prop-protection-master/lua/fpp/server/core.lua (line 658)]

[ERROR] lua/includes/util.lua:181: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:181
   2. unknown - RunString:121

Timer Failed! [Simple][@RunString (line 118)]

[ERROR] lua/includes/util.lua:181: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:181
   2. unknown - RunString:121

Timer Failed! [Simple][@RunString (line 118)]

[ERROR] lua/includes/util.lua:181: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:181
   2. unknown - RunString:121

Timer Failed! [Simple][@RunString (line 118)]

[ERROR] lua/includes/util.lua:181: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:181
   2. calculateCanTouchForType - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:113
    3. calculateCanTouch - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:169
     4. onEntitiesCreated - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:337
      5. unknown - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:352

everytime someone joins,
these serverside errors occur.

**Comment by FPtje** [comment]
Some addon is fucking up CPPI by returning a number for `ent:CPPIGetOwner`.
