### ISSUE TITLE
Add option for restricting admins physics/tool usage on map created entities

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/Falcos-Prop-protection#197]
this feature should be in, as stupid admins are flying over the server moving func_* things.
I created a work around, but it does not work flawlessy with fpp

**Comment by FPtje** [comment]
There's a block list for a reason.

**Comment by mcNuggets1** [comment]
But not for map entities like prop_physics.

**Comment by FPtje** [comment]
Something something world entities

**Comment by mcNuggets1** [comment]
Yea, but that restricts non map entities too, like money printers in DarkRP.

**Comment by FPtje** [comment]
The options are there. I cannot fix your inability to use them.

**Comment by mcNuggets1** [comment]
If you set Admins can pickup world entities to false, map entities can't be picked up, but some entities can't be picked up either.
But there is no option for just disabling pick up of map created entities, without adding thousands of entries to the white/blocklist.

**Comment by FPtje** [comment]
What is the difference between world entity and map entity supposed to be?

**Comment by mcNuggets1** [comment]
World entities are entities owned by world and map entities are entities which are generated from the map.

Mapentities return true on meta:CreatedByMap() (serverside).

**Comment by FPtje** [comment]
Any entity that doesn't have an owner set is considered to be owned by the map. Map is a synonym of world. Suggesting that the words map and world should mean different things is utmost ridiculous.

**Comment by FPtje** [comment]
Looks like the problem you're having is not that you can't find the "admins can touch world props" option, but that your money printers don't have an owner set.

**Comment by mcNuggets1** [comment]
They have, but not with CPPISetOwner.

**Comment by FPtje** [comment]
Not my responsibility, unless you're talking about the default DarkRP money printers

**Comment by mcNuggets1** [comment]
The normal printers are considered as world entities, because they are set with Setowning_ent, but not with CPPISetOwner.

**Comment by mcNuggets1** [comment]
My suggestion is adding an option for disabling the pick up of entities created by the map.
Not with a lua script.

**Comment by FPtje** [comment]
Your suggestion would separate definitions of "world" and "map". I hope you understand that this would be ridiculous.

**Comment by mcNuggets1** [comment]
They are already separated by gmod itself.

I just asked for an option to check if meta:CreatedByMap() returns true, ending up in disabling the pickup/removation etc.
I now have to use an extremly ugly workaround for that.

On mapstartup I take all entities created by map and put it in a table.
If physgunned entity is in table return false.

**Comment by FPtje** [comment]
Where does GMod specify the meaning of "world"? If it doesn't how can it separate it from "map"?

**Comment by FPtje** [comment]
specify or use, like it uses "map" in `:CreatedByMap()`

**Comment by mcNuggets1** [comment]
Normally you can pickup all entities in GMod.
So it doesnt really explain world entities too, you are doing that.

I dont want a new definition of world entities named map.
I just want to disable the pickup and tool usage on map created entities, because it is not possible in FPP without messing up everything.

**Comment by FPtje** [comment]
There is an option called "Admins can touch world entities"
you want an option called "admins can touch map created entities"

Those would be separate options. They would do different things. One talks about a "world" and the other talks about a "map". You expect people to understand what the difference between those options would be? 

There is no difference between "world" and "map". There's only a difference between what FPP considers "world **ENTITIES**" and "map created **ENTITIES**".

**Comment by mcNuggets1** [comment]
That is pretty easy to understand.
Also alot of people having issues with admins fucking around with deleting map created entities etc.
The userbase would love it.

I don't get, why it is such a problem for you, to understand why I am suggesting that.

**Comment by FPtje** [comment]
because map created props ⊆ world props.

**Comment by mcNuggets1** [comment]
There is a slightly differance.

Map created entities, not always props. -> Nobody wants them to get touched and dragged aways anyways.

World entities, like money printers and other entities -> Is not owned by anyone, but people want admins to be able to touch them or delete them.

**Comment by FPtje** [comment]
You cannot explain the difference between "map" and "world" without invoking entities. That's fundamentally ridiculous.

**Comment by mcNuggets1** [comment]
We dont need to explain the difference.
Just an option would be nice.

Not only for me, especially for me, because I made a workaround for that.

**Comment by FPtje** [comment]
An option for something you're unable to explain. Not going to happen.

**Comment by mcNuggets1** [comment]
Map created entities are entities which are not created with Lua, instead by the map itself.

**Comment by FPtje** [comment]
So far you've been really good at talking about entities. Can you talk about the difference between "map" and "world"

# WITHOUT MENTIONING ENTITIES?

**Comment by mcNuggets1** [comment]
The world is a planet.
The map is a specified region.

I didnt want to define the defintion of two words.
I was just suggesting an option for FPP to disable physgun/toolgun **_**ENTITIES**_** created by the map and not lua.
On many servers the owners have problems with especially that.

**Comment by Bo98** [comment]
He probably wants their definitions in a GMod context, otherwise I imagine a dictionary would've been consulted.

I guess you could say the "world" is the world entity (`game.GetWorld()`) and the "map" is the BSP loaded.

**Comment by FPtje** [comment]
@Bo98 you son of a bitch, haha

**Comment by FPtje** [comment]
Anyway, all map created entities are world entities. After all, world entities are entities without an owner. Map created entities have no owner. If there's an option about admins touching map created entities, then map created entities would be affected by two options. That gets very confusing very fast. Even if everyone somehow understands the difference between "map" and "world".

**Comment by mcNuggets1** [comment]
That is not really confusing tho.

If you disallow touching of map created entities, then this only affects entities which return true on meta:CreatedByMap() and if you disallow touching world entities, then it only disallows touching of entities with no owner.

**Comment by FPtje** [comment]
It would be confusing for me to implement.

This option is not going to happen. Full stop.
