### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by sw2719** [FPtje/Falcos-Prop-protection#198]
[ERROR] lua/includes/util.lua:181: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:181
   2. calculateCanTouchForType - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:114
    3. calculateCanTouch - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:170
     4. onEntitiesCreated - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:342
      5. unknown - addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua:357

Timer Failed! [FPP_OnEntityCreatedTimer][@addons/falcos-prop-protection-master/lua/fpp/server/ownability.lua (line 365)]

server console spammed with this error.

gamemode : sandbox

**Comment by FPtje** [comment]
some addon setting `ply.Buddies`.
