### ISSUE TITLE
Addons with constrained.

### ISSUE THREAD

**Issue by RedTailedHawkSTM** [FPtje/Falcos-Prop-protection#199]
How can I add code to an addon so we can physgun it? i know its the "creators" fault but I can't find out how to un-constrain things.

**Comment by RedTailedHawkSTM** [comment]
I realize this is not an "issue" but I don't know where else to ask.

**Comment by FPtje** [comment]
The most universal way would be to do nothing with fpp and just use the physgun hooks.
