### ISSUE TITLE
FPP Remove Bug

### ISSUE THREAD

**Issue by Flodel01** [FPtje/Falcos-Prop-protection#200]
Users can delete world's entities like this: (we modify and "word" on the picture is in red but we can delete this)
![bug](https://cloud.githubusercontent.com/assets/23125672/19815584/dc30c762-9d43-11e6-946e-a8f8ddd143bb.png)

But I can't delete this:
![bug2](https://cloud.githubusercontent.com/assets/23125672/19815759/9f428b6e-9d44-11e6-841f-a5d5e94bc99d.png)

**Comment by FPtje** [comment]
Misconfiguration is not a bug.

**Comment by Flodel01** [comment]
And how can I do to fix this ?
