### ISSUE TITLE
ULX admin group can't spawn props.

### ISSUE THREAD

**Issue by Sparks5** [FPtje/Falcos-Prop-protection#202]
Alright, hi. I'm the server manager of a server, with DarkRP as a base gamemode, and we're slightly re-structuring staff. We have a sort of administrative supervisor rank, they inherit from Admin but they cannot spawn props. I've looked around a bit, seen FPtje say that you can just make an FPP group with the same name as the ULX group and have set up correctly (which I've tried and it was set up correctly) and it will work from there. It doesn't.

The ulx group name is "headadmin". Just like that.
The FPP team name is "headadmin". Also just like that. They're set to allow all tools.

They both have the same name, The headadmin ULX group has the same permissions as Admin, which CAN spawn props, but headadmin cannot.

How do I make a ULX group (which inherits from a group that CAN spawn props) able to spawn props?

**Comment by FPtje** [comment]
Spawning props doesn't happen through tools. Changing settings in FPP about groups being allowed to use tools doesn't affect the spawning of things. It affects the usage of tools instead. In FPP you can blacklist some models of props, but that's about it when it comes to spawning. 

If you want to figure out why head admins can't spawn props, you should look at the message they get when they try. Is the prop blacklisted? Not whitelisted? Is some other addon blocking things?
