### ISSUE TITLE
FPP and ULX arent working together

### ISSUE THREAD

**Issue by herpbrownstainz** [FPtje/Falcos-Prop-protection#206]
when ever i disable ULX i can use the FPP settings but if i enable the ULX it says this 
You need the 'FPP_Settings' privilege in order to be able to use this command
plz help

**Comment by FPtje** [comment]
Give yourself the privilege through ulx. Also not a help forum.

**Comment by herpbrownstainz** [comment]
Oh dry for not a help forum and I think I solved it(ulx not up to date)
