### ISSUE TITLE
ERROR creating timer

### ISSUE THREAD

**Issue by DaleAGaming** [FPtje/Falcos-Prop-protection#207]
[ERROR] lua/includes/util.lua:181: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:181
   2. calculateCanTouchForType - addons/fpp/lua/fpp/server/ownability.lua:114
    3. calculateCanTouch - addons/fpp/lua/fpp/server/ownability.lua:170
     4. onEntitiesCreated - addons/fpp/lua/fpp/server/ownability.lua:342
      5. unknown - addons/fpp/lua/fpp/server/ownability.lua:357
 
Timer Failed! [FPP_OnEntityCreatedTimer][@addons/fpp/lua/fpp/server/ownability.lua (line 365)]

**Comment by FPtje** [comment]
Some addon set the CPPI owner of some entity to a number. That or someone sets the `Buddies` fields of players to a number.

Either way, it's an external addon interfering. I don't know which one, though.
