### ISSUE TITLE
Wire Expression 2 does not work correctly with admins

### ISSUE THREAD

**Issue by Fasteroid** [FPtje/Falcos-Prop-protection#210]
Wire Expression 2 seems to not have a proper bypass set in place for admins.

As it is currently admins still need to be buddied by lower players in order to use any wiremod e2 functions on their props. For example, if I as an admin wanted to remove a prop owned by another player named Derp THROUGH an e2 function, Derp would have to buddy me before I could remove his prop. Since I'm an admin though, I shouldn't need this permission. Please note all other bypasses work for me, e2 is the only thing that seems to be ignoring the admin check.

Hope this can be looked into soon, as it is currently getting in the way of something I'm trying to make that deals with server cleanup.

**Comment by FPtje** [comment]
FPP has a thing called CPPI. It allows addons to query whether the prop protection allows a player to do something with a prop. All major pro protections have this. Wiremod uses it, I believe, but I don't know how it deals with expression 2 functions.

Whatever they do is their decision, though. CPPI should make it possible for them to make what you want. Once they do so, it will work with any major prop protection.

**Comment by Fasteroid** [comment]
> Referring to propDelete, and everything else in propcore, it checks if the player is friends with the entity's owner. I assume when Falco said
> 
> It allows addons to query whether the prop protection allows a player to do something with a prop.
> 
> he's talking about the CPPICan* functions, however none of them would fit the use case of deleting a prop (for example) as far as I can tell.
> 
> Edit: Looking over the CPPI Doc for CPPIGetFriends it says
> 
> Returns the friends of a player, other players who are allowed to manipulate the specified player's objects.
> 
> Which I assume means it should returns the admins as well, even if they aren't friends. So this should be fixed if FPP included the admins in the returned friends list. Unless it does that already in which case I don't know where this goes wrong.

This is what was said when I posted the issue on the wiremod github page. I'll also give you a few falco configuration details so you can hopefully identify what the problem is.

 - I am able to physgun anybody's props
 - I am able to toolgun anybody's props
 - I seem to be able to use the E2 Tool on anybody's props.
 - Functions like propDelete only work on players who have buddied me.
 - Functions like applyForce will ONLY work on your own props.
 - Plycore functions (preformed on players) seem to work just fine. As expected they do nothing when run on props.

**Comment by FPtje** [comment]
What CPPI functions are called when you do these things? 
applyForce may be affected by FPP's e2 antiminge system.
