### ISSUE TITLE
Cant turn off dupe spam option

### ISSUE THREAD

**Issue by kaisar1234** [FPtje/Falcos-Prop-protection#212]
I was trying to use the anti spam and then I noticed that the duplicator anti spam only goes up to 10 and you cant turn it off either. Can you make it so you can turn off the anti spam dupe nobody on my server can spawn a dupe without it restricting the the tenth prop. The only way to turn it off is to turn the whole antispam off. I tried setting duplicator protection to 0 in the sh_settings.lua file but it did nothing. If you can  
find a way to fix it that would be awesome let me know if you do. Your mod is great and I have been using it for 2 years now.

**Comment by FPtje** [comment]
In latest version, set to 0 to disable.
