### ISSUE TITLE
Bad inline model number 300

### ISSUE THREAD

**Issue by EternalStorm** [FPtje/Falcos-Prop-protection#213]
when i view the blocked models list i get the above error.

**Comment by FPtje** [comment]
Screenshot?

**Comment by EternalStorm** [comment]
it just crashes to desktop with an error box saying it, theres no point screenshoting

**Comment by FPtje** [comment]
Could you give me a list of your blocked models?

**Comment by EternalStorm** [comment]
how do i exactly?

**Comment by FPtje** [comment]
Do you use MySQL or the default settings?

**Comment by EternalStorm** [comment]
default

**Comment by FPtje** [comment]
On the **server** console (rcon):

```
lua_run MySQLite.query("SELECT * FROM FPP_BLOCKEDMODELS1", function(d) for k,v in pairs(d) do print(k, v) end end)
```

The result should appear in the server console

**Comment by EternalStorm** [comment]
nothing came up, as im not the owner someone did it for me

**Comment by FPtje** [comment]
First run this in rcon:

```
lua_run file.Write("fart_beans.txt", "\n")

```

Then this:
```
lua_run MySQLite.query("SELECT * FROM FPP_BLOCKEDMODELS1", function(d) for k,v in pairs(d) do file.Append("fart_beans.txt", tostring(k) .. " -> " .. tostring(v) .. "\n") end end)
```

On the *server*, a file should appear in `garrysmod/data` called `fart_beans.txt`. Upload that file here.

**Comment by FPtje** [comment]
Any luck?
