### ISSUE TITLE
CVars?

### ISSUE THREAD

**Issue by blizzard2023** [FPtje/Falcos-Prop-protection#214]
Hello,

I wanted to know if any CVars exist for FPP. I am trying to make it so by default people have the private setting "I don't want to see the owners of props" unchecked.

Thanks,
Blizzard

**Comment by roboderpy** [comment]
*All that she wants, is control over **entrie player's clients** *
![5b209de993_discordcanary_2017-08-14_17-25-37](https://user-images.githubusercontent.com/6339511/29268099-9ce4f8d8-8115-11e7-936a-e1b315a71ae3.png)
![cea00057a8_discordcanary_2017-08-14_17-25-54](https://user-images.githubusercontent.com/6339511/29268105-a282282e-8115-11e7-9b7e-4c436400567c.png)
![ebb6814f31_discordcanary_2017-08-14_17-28-23](https://user-images.githubusercontent.com/6339511/29268247-31f72130-8116-11e7-8ebd-79dd23ceed99.png)
![cea00057a8_discordcanary_2017-08-14_17-25-54](https://user-images.githubusercontent.com/6339511/29268246-31f53924-8116-11e7-853f-a379299d8857.png)

Messing with default player's options is not funny. Can you all just stop that?

@FPtje thats why gmod community dies

**Comment by blizzard2023** [comment]
I own a serious to server and I'm pretty sure a majority of my players do
not want to see "world" every time they look at a world prop.

**Comment by roboderpy** [comment]
if they don't want to, they can disable it **by themselves**

**Comment by blizzard2023** [comment]
Or I can disable it for them considering it's serious rp and your not
supposed to have much of a hud with the gamemode Im using? All im doing is
making the little world thing on the left disappear with the car that's
all. No need to get passive aggressive with me.

**Comment by roboderpy** [comment]
After client startup, remove FPP's HUD hooks if local player is not an admin. isn't that simple?

**Comment by FPtje** [comment]
They're private settings. Not server settings.

**Comment by FPtje** [comment]
Changing them on a client would affect not only your server, but every server they join. You have no right to decide players' experience on other servers.
