### ISSUE TITLE
Player cannot interact with their own Props

### ISSUE THREAD

**Issue by SharkGamiing** [FPtje/Falcos-Prop-protection#215]
First think my English isnt very good.
No one on my Server can Interact with their own Props.
On the Left are standing blocked and not the Name of The Owner of the Prop.
I dont now what i can do. I look every where but i found nothing.

[http://i.imgur.com/Cdsw3Ux.jpg?1](url)

I know its green but I am Admin .
By a Normal Player (User) its red and he cannot Pickup his Prop.

**Comment by FPtje** [comment]
Not a help forum
