### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by BasonTaylor** [FPtje/Falcos-Prop-protection#216]
Okay Your prop protection is easy to use and fantastic at that but the only 2 things i have a issue with is Players can prop push players still AND Vehicles i dont know if there is a setting to enable this but in my opinion i think you should add thoughts as a check marks to enable or disable them Sorry i may be over stepping my bounds but i see this used and minged with on alot of servers. Even my own So my solution is when a player picks up a prop make it no-collided/Ghosted until person puts the prop down And can go through only Users and Vehicles Not other props... If this can be worked on or fixed ithink this can be the best prop protection out there thats the one thing we need to stop the users from minging

**Comment by FPtje** [comment]
Fuck no. Gmod is much more fun when the physics engine isn't fucked up and over by some shitty addon that has saving admin effort as its only purpose.

**Comment by BasonTaylor** [comment]
so basically saying fuck the user experience okay thanks for your 100% awesome help

**Comment by BasonTaylor** [comment]
not every server has admins on 100% of the time its not to save there asses its to save the users whom play the damn thing

**Comment by roboderpy** [comment]
You can try another addon instead of complaining about developer decisions.

**Comment by BasonTaylor** [comment]
its disgusting when some one makes a game mode made for role play and basically says fuck the players man you obviously are the Bacteria at the bottom of the gmod barrel no wonder the gmod community is so cancer its because of your shit code for dark rp because you care nothing for what others like and shove it up there ass you think you are so high brow when every one has a question you say Fuck fixing it its fun watching you suffer good effort i wonder how much you actually do its adorable really. you bitch and moan others use it in other catigorys who care your the idiot who released the damn game mod stop complaining about what people do with it you made it free for every little bastered and there mom Fuck you man really is see this careless BS all The time you should fix you code or fuck off.

**Comment by roboderpy** [comment]
i died

**Comment by Bo98** [comment]
> Sorry i may be over stepping my bounds

> fix you code or fuck off

**Comment by FPtje** [comment]
This shit used to be in FPP before anyone else even decided to build their own solution. I removed it because it can be circumvented, or it significantly harms gameplay. Usually both. Pretty much all the addons I've come across that do this make everything physics related *really* annoying. Many of them can also still be circumvented easily enough.

I'm not implementing this. No amount of bitching is going to make me.
