### ISSUE TITLE
Players cant pickup their own props

### ISSUE THREAD

**Issue by AquaRex** [FPtje/Falcos-Prop-protection#217]
Im pretty sure you've heard about the problem before, i seem unable to find any solutions to this, and changing any setting including turning prop protection off does not solve this problem. I have no other prop-protection addons installed.  

If i spawn a prop on my server, this error is thrown into the console: 

[ERROR] lua/includes/util.lua:181: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:181
   2. entGetTouchReason - gamemodes/darkrp/gamemode/modules/fpp/pp/client/ownability.lua:80
    3. fn - gamemodes/darkrp/gamemode/modules/fpp/pp/client/hud.lua:159
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:179

(prop is also owned by "unknown player")
I dont know if this is a problem with your addon or not, if this isnt a problem with your addon, could you help point me in the right direction?

**Comment by FPtje** [comment]
The error you've given me is clientside. You not being able to touch entities is a server side issue. There's probably a ton of errors there.

Another cause may be some addon messing everything up. FPP doesn't make you unable to touch anything when it's disabled. It must be something else.
