### ISSUE TITLE
I'm having an issue with adding FPP onto my server

### ISSUE THREAD

**Issue by Coenio** [FPtje/Falcos-Prop-protection#219]
A buddy and I are attempting to make a Basewars server on GMOD and we both have tried adding FPP to our server, I am not sure if we are trying to use the wrong version or we are just putting the addon in the incorrect folder, I just have Falcos-prop-protection-master in the addons folder of the server. 
This is the list of addons we currently have on the server, this is the folder I assume that we are supposed to upload FPP because I downloaded as an addon.
![screenshot_1](https://user-images.githubusercontent.com/7015665/32472957-b995944a-c32a-11e7-8da6-fcb054748411.png)

**Comment by roboderpy** [comment]
Rename directory to `falcos-prop-protection-master` or even `fpp`

**Comment by Coenio** [comment]
Thank you so much, its working now.

**Comment by roboderpy** [comment]
Close the issue by pressing `Close issue` near `Comment`

This helps everyone a lot
