### ISSUE TITLE
Trying to write an e2 extension that shares props and have no idea how to do it

### ISSUE THREAD

**Issue by Fasteroid** [FPtje/Falcos-Prop-protection#224]
@FPtje , remember me from about a year ago, the one who was complaining about e2 not working?
I need your help again but this time I actually know a little bit of LUA.

Let me just say I was an idiot before. I didn't know any LUA.

I want to make an e2 extension now that allows me to share props with people. I know how to make these e2 commands in lua already but when it came time to try and clone whatever goes on inside the prop share tool into it, I was stumped. I didn't make fpp so I really don't have a clue as to how it works.

I've attached my e2 extension (not finished yet, I did as much as I could)
I left comments in the code detailing how wire e2 functions work in lua and a brief explanation of what this one should do if you decide to help me.

[propsharecorebutitsatextfilebecausegithubsaysnonoonoootoluafiles.txt](https://github.com/FPtje/Falcos-Prop-protection/files/1630158/propsharecorebutitsatextfilebecausegithubsaysnonoonoootoluafiles.txt)

**Comment by FPtje** [comment]
Serverside an entity has these variables:

```lua
this.SharePhysgun1
this.ShareGravgun1
this.SharePlayerUse1
this.ShareEntityDamage1
this.ShareToolgun1
```
Each controls whether it's shared for physgun stuff, gravgun stuff, getting used by a player, getting damaged by a player and being used the toolgun on. Set to `true` to enable sharing, set to `false` or `nil` to disable sharing.

You won't have to send the usermessage. FPP will do that for you when necessary.

After setting these variables, make sure to run `recalculateCanTouch(player.GetAll(), {this})` for the entity of which you changed the sharing settings. Here's why: FPP only calculates whether players can touch things when the settings change. You want to change the settings, so you have to push FPP to recalculate who can touch what.

I'll mark the issue as resolved, but you can post here if you have more questions.

**Comment by Fasteroid** [comment]
I'm guessing those variables change share permissions for all players?

**Comment by FPtje** [comment]
Yes

On 15 Jan 2018 3:12 pm, "Fasteroid" <notifications@github.com> wrote:

I'm guessing those variables change share permissions for all players?

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/FPtje/Falcos-Prop-protection/issues/224#issuecomment-357693571>,
or mute the thread

**Comment by Fasteroid** [comment]
Perfect, thanks falco. I'mma try it and see if it works
[propsharecorebutitsstillatextfilebecausegithubsaysnonoonoootoluafiles.txt](https://github.com/FPtje/Falcos-Prop-protection/files/1632324/propsharecorebutitsstillatextfilebecausegithubsaysnonoonoootoluafiles.txt)

**Comment by FPtje** [comment]
Not this:
```lua
if(perm == "physgun") then
	local Physgun = this.SharePhysgun1 or true
end
```

this:
```lua
if(perm == "physgun") then
	this.SharePhysgun1 = true
end
```
