### ISSUE TITLE
Use NW2

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/Falcos-Prop-protection#225]
I would suggest using Nw2 as they are way more effective.

**Comment by FPtje** [comment]
I can't be arsed dealing with the PVS issues.

**Comment by mcNuggets1** [comment]
The nw strings used are only used clientside when the entity is in the pvs of the player.
Thats the whole reason this change would make sense.

**Comment by FPtje** [comment]
But having an NW2Var isn't? Aside from PVS they're the exact same thing with a different implementation.

**Comment by mcNuggets1** [comment]
But it won't network the var to you, when you are not near the entity.
Thats a improvement.

**Comment by FPtje** [comment]
PR it

**Comment by FPtje** [comment]
But make sure neither FPP nor addons using CPPI need the values of those thing outside PVS.
