### ISSUE TITLE
Group tool Restriction Error

### ISSUE THREAD

**Issue by Metal-Fish** [FPtje/Falcos-Prop-protection#231]
And when I load the groups user's names aren't loaded
https://i.imgur.com/CZw8moU.png

When I add someone to group tool restriction I get the following error that the list might be corrupt and a reload is recommended
https://i.imgur.com/xoPgHWF.png

Also people with the same rank are auto-synced to their group.

How can I fix this?

**Comment by FPtje** [comment]
You have to load/reload every time you open the menu or make a change. Shitty, but not really worth my time changing.

With all changes you make, that corrupted message is shown. It just means you gotta reload.

People with their usergroup equal to a group in that list are synced to that group, the message above explains that:

> NOTE: People who have the
> usergroup that matches with this group
> are automatically in this group!

**Comment by Metal-Fish** [comment]
My only concern is that people aren't auto synced when they have the same group, I have to manually add them. I have people in the ulx member group that aren't automatically placed in the FPP member group. Is there something I'm doing wrong?

**Comment by FPtje** [comment]
FPP uses usergroups to determine what group they're in. If a player's usergroup is `member`, then they will be in the FPP `member` group.

**Comment by Metal-Fish** [comment]
The MySQL database doesn't reflect that, could you try it to see if it's just me not doing it right?

**Comment by FPtje** [comment]
The `member` group won't exist in FPP until you manually create it in FPP. Creating the group won't make it appear in FPP. You'll still have to create the group in FPP. 

Players with the `member` usergroup will /implicitly/ be in the `member` FPP group. That means it's not stored in the database.

**Comment by Metal-Fish** [comment]
This is what's leading to my confusion as I have both already set up.

https://i.imgur.com/P7clVFd.png

https://i.imgur.com/ZWVgymB.png

**Comment by FPtje** [comment]
They won't show under group members if it's their usergroup IIRC

**Comment by Metal-Fish** [comment]
I know this isn't the place to ask but how exactly does grouping interact with tools that you set to admin/superadmin only. Does it override them? Or do you set the tool for everyone then have it set through group tools?

**Comment by FPtje** [comment]
IIRC it's an and-and situation. If tool A is admin only and allowed for group B, then non-admin player X in group B won't be able to touch it, because X has to be both admin AND in group B.

Advice is not to combine them, it's confusing.

**Comment by Metal-Fish** [comment]
Makes sense to me, thanks a lot for clarifying all this stuff!
