### ISSUE TITLE
Cannot find FPP files

### ISSUE THREAD

**Issue by Ilunga1** [FPtje/Falcos-Prop-protection#233]
I've been looking through my addons folder, including DarkRP modification master, and I seem to not be able to find the files.

I have this installed and in-game it runs fine, just can't find the files via ftp?

**Comment by Bo98** [comment]
It's a part of the gamemode. Why do you need to know?

**Comment by Ilunga1** [comment]
mysql support. I'm also pretty sure I had to install this.
