### ISSUE TITLE
lua/includes/util Causing errors for FPP

### ISSUE THREAD

**Issue by MicahJinkerson** [FPtje/Falcos-Prop-protection#236]
`L 09/10/2018 - 19:09:36: Lua Error: 
[ERROR] lua/includes/util.lua:204: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:204
   2. netWriteEntData - addons/fpp/lua/fpp/server/ownability.lua:265
    3. plySendTouchData - addons/fpp/lua/fpp/server/ownability.lua:276
     4. onEntitiesCreated - addons/fpp/lua/fpp/server/ownability.lua:351
      5. unknown - addons/fpp/lua/fpp/server/ownability.lua:360
 
 
 
[ERROR] lua/includes/util.lua:204: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:204
   2. netWriteEntData - addons/fpp/lua/fpp/server/ownability.lua:265
    3. plySendTouchData - addons/fpp/lua/fpp/server/ownability.lua:276
     4. onEntitiesCreated - addons/fpp/lua/fpp/server/ownability.lua:351
      5. unknown - addons/fpp/lua/fpp/server/ownability.lua:360
 
Timer Failed! [FPP_OnEntityCreatedTimer][@addons/fpp/lua/fpp/server/ownability.lua (line 368)]`

` 
[ERROR] lua/includes/util.lua:204: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:204
   2. netWriteEntData - addons/fpp/lua/fpp/server/ownability.lua:265
    3. plySendTouchData - addons/fpp/lua/fpp/server/ownability.lua:276
     4. recalculateCanTouch - addons/fpp/lua/fpp/server/ownability.lua:215
      5. callback - addons/fpp/lua/fpp/server/ownability.lua:228
       6. callback - addons/fpp/lua/fpp/sh_settings.lua:131
        7. Call - addons/fpp/lua/libraries/sh_cami.lua:357
         8. PlayerHasAccess - addons/fpp/lua/libraries/sh_cami.lua:370
          9. calculatePlayerPrivilege - addons/fpp/lua/fpp/sh_settings.lua:133
           10. recalculateCanTouch - addons/fpp/lua/fpp/server/ownability.lua:228
            11. unknown - addons/fpp/lua/fpp/server/ownability.lua:500
 
Timer Failed! [FPP_recalculate_cantouch_3][@addons/fpp/lua/fpp/server/ownability.lua (line 499)]
L 09/10/2018 - 19:01:47: Lua Error: 
[ERROR] lua/includes/util.lua:204: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:204
   2. netWriteEntData - addons/fpp/lua/fpp/server/ownability.lua:265
    3. plySendTouchData - addons/fpp/lua/fpp/server/ownability.lua:276
     4. onEntitiesCreated - addons/fpp/lua/fpp/server/ownability.lua:351
      5. unknown - addons/fpp/lua/fpp/server/ownability.lua:360
 
 
 
[ERROR] lua/includes/util.lua:204: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:204
   2. netWriteEntData - addons/fpp/lua/fpp/server/ownability.lua:265
    3. plySendTouchData - addons/fpp/lua/fpp/server/ownability.lua:276
     4. onEntitiesCreated - addons/fpp/lua/fpp/server/ownability.lua:351
      5. unknown - addons/fpp/lua/fpp/server/ownability.lua:360`

Please dear god fix this

**Comment by roboderpy** [comment]
Not a FPP issue but an installed addon issue

@FPtje add an `assert` on `CPPISetOwner` function on `owner` object so people will see which addon do dumb stuff.

**Comment by FPtje** [comment]
blergh
