### ISSUE TITLE
Argument(s) invalid

### ISSUE THREAD

**Issue by cameronjacob** [FPtje/Falcos-Prop-protection#237]
Saw this error earlier in a GitHub issue, seems to be a problem for me too. Tried re-installing FPP from this GitHub, FPP from the DarkRP github, and the workshop collection, but none seem to help. Every time I try to change anything FPP related I get "Argument(s) invalid". I'm using serverguard if that is helpful.

EDIT: Updated to latest DarkRP, still an issue.

**Comment by FPtje** [comment]
I think this can happen if you have multiple versions of FPP installed. If you run DarkRP, remove ALL addons referring to FPP. DarkRP has FPP in it, so versions in the addon folder or even the workshop version of FPP can conflict.

Can you tell me if that solved the problem?

**Comment by FPtje** [comment]
I've updated FPP, FPP workshop and FPP in the Github version of DarkRP with the above commit. (Workshop version of DarkRP hasn't been updated yet). 

If you update, instead of `Argument(s) invalid` you'll get a better error. That'll help debug the problem.

**Comment by cameronjacob** [comment]
I have DarkRP installed under /gamemodes/darkrp as well as through the Workshop. Could this be causing the issue?

**Comment by FPtje** [comment]
That's very peculiar. I actually bet on the "setting does not exist" error being thrown instead. Nevertheless this does point us towards finding the cause of the problem. I'm thinking one possible cause is a dumb addon overriding `RunConsoleCommand` with only two arguments. That should break more stuff than just FPP though.

To test this, I'm going to ask you to do two seemingly unrelated things:

- Buy a door, open the keys menu on the door and add another player as owner of the door. Note: this test only makes sense if the keys menu hasn't been changed by an addon
- Spawn a shipment, take a weapon from it, open context menu (bound to `c` by default) and click `make a shipment`

If my hypothesis is right, the above two things should NOT work, as they also use RunConsoleCommand with more than two arguments. If those two things *do* work, then we'll have to look somewhere else.

**Comment by cameronjacob** [comment]
Using a bot I get a `Could not find NULL` error, but I'm unsure if this is because it is a bot or not. Regardless, I don't see `Make a shipment` anywhere in the context menu. Was there a step somewhere I missed on that one?

**Comment by Bo98** [comment]
With the `c` menu open, you right click on a weapon on the ground and it should appear as an option.

You should also post any errors you get in full.

**Comment by Bo98** [comment]
Take this menu for example:

![](http://i.imgur.com/btnbzQ7.png)

Does the issue happen with the checkboxes, the sliders or both?

**Comment by cameronjacob** [comment]
Both.

**Comment by FPtje** [comment]
@cameronjacob could you send me an email with your server details? I'd like to try some things. I don't think I'll need superadmin access, but I do need `sv_allowcslua 1`, so I can log what commands FPP is sending when I click the buttons.

**Comment by FPtje** [comment]
Nvm found you on steam

**Comment by FPtje** [comment]
Alright, we found the issue. Turns out my suspicion was right.

This addon right here is the cause:
https://steamcommunity.com/sharedfiles/filedetails/?id=1445870911

**THAT ADDON WILL BREAK FPP**

Here's how:

```
function RunConsoleCommand(command, args, argStr)
	if string.Left(command, 7) == "connect" then args = args or "nil" print("blocked: " .. command .. " " .. args) HandleConnectionAttempt(args, debug.getinfo(2)) return end
	return RCC(command, args, argStr)
end
```
Only two arguments, no varargs. Exactly as I suspected.

If you have this problem, remove this addon!

**Comment by JoeKoen** [comment]
> Alright, we found the issue. Turns out my suspicion was right.
> 
> This addon right here is the cause:
> https://steamcommunity.com/sharedfiles/filedetails/?id=1445870911
> 
> **THAT ADDON WILL BREAK FPP**
> 
> Here's how:
> 
> ```
> function RunConsoleCommand(command, args, argStr)
> 	if string.Left(command, 7) == "connect" then args = args or "nil" print("blocked: " .. command .. " " .. args) HandleConnectionAttempt(args, debug.getinfo(2)) return end
> 	return RCC(command, args, argStr)
> end
> ```
> Only two arguments, no varargs. Exactly as I suspected.
> 
> If you have this problem, remove this addon!

Hello, im the author for this plugin: https://steamcommunity.com/sharedfiles/filedetails/?id=1445870911
I will fix this right away!
Sorry for causing trouble to people with this issue.

**Comment by FPtje** [comment]
Awesome, thanks!
