### ISSUE TITLE
Props/Entities keep ghosting even with the anti-prop settings being off

### ISSUE THREAD

**Issue by elfonashelf** [FPtje/Falcos-Prop-protection#241]
Me and my server developers are confused because all our props and entities keep ghosting when all the anti-prop settings are off like none of the boxes are ticked and they keep ghosting please help

**Comment by FPtje** [comment]
Fpp doesn't ghost when antispasmodic settings are off. Check for other addons like anti prop kill shit. They love ghosting everything always forever

**Comment by elfonashelf** [comment]
I've had a look at our content pack and the addons folder on the server panel. We don't have any anti prop kill addon the only addon that we have which does anti prop stuff is this one also it came with the darkrp mode so i can't delete it and reinstall it.

**Comment by FPtje** [comment]
Do you get a message when something gets ghosted? FPP always shows mlsome message

**Comment by elfonashelf** [comment]
It didn't show a message when its ghosted like what it does when the setting are on. I have a theory that its VJbase because since we got that it started.
