### ISSUE TITLE
help me please

### ISSUE THREAD

**Issue by ParksRR** [FPtje/Falcos-Prop-protection#245]
I am on gmod I am Superadmin for some reason I cannot edit fpp I have access to all commands I cant edit fpp please help I cannot pick up players props either and a lower use group can that has less perms
![image](https://user-images.githubusercontent.com/47246955/55658793-cd554680-57f6-11e9-8960-4721e392f62a.png) for more ss's or proof just ask

**Comment by ParksRR** [comment]
![image](https://user-images.githubusercontent.com/47246955/55658824-f675d700-57f6-11e9-961a-89baade36dbb.png)

**Comment by FPtje** [comment]
Your client doesn't believe that you're superadmin. Please head to forum.darkrp.com for more help.
