### ISSUE TITLE
Fix MYSQL

### ISSUE THREAD

**Issue by ZokeysEPN** [FPtje/Falcos-Prop-protection#246]
Hey,
Currently on sandbox, and I have newer mysql modules and it doesn't seem to work.
It can't even create the tables but it's connected.
Also, the mysql files directs to older modules, which are not supported and links dont work anymore too.
Could you fix it?
Thanks.

**Comment by FPtje** [comment]
Can you give me a link to the version of MySQL module you're using?

**Comment by ZokeysEPN** [comment]
https://forum.facepunch.com/f/gmodaddon/jjdq/gmsv-mysqloo-v9-Rewritten-MySQL-Module-prepared-statements-transactions/1/

**Comment by FPtje** [comment]
The problem was actually with the MysQLite throwing an error when loaded before the gamemode. Thanks for the bug report!

**Comment by ZokeysEPN** [comment]
It's working. Thanks so much for the great and fast support.
