### ISSUE TITLE
FPP denies hook calls, uses blank returns on code end

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/Falcos-Prop-protection#249]
FPP denies the hook calls of PhysgunPickup, OnPhysgunReload, GravGunPickupAllowed, GravGunPunt, PlayerUse, EntityTakeDamage, CanEditVariable, CanTool and maybe even more, but that were the hooks I found, when certain conditions are met.

core, Line 132:
FPP looks up if the entity has a PhysgunPickup function written onto it or if Physgun Pickup is disabled.
There should be nothing wrong with it, if it weren't returning SOMETHING, if the function returned a var, thus preventing any other hooks from getting called.
You may call the function to check if Physgun pickup is allowed, but not prevent every other hook from calling, it's a no go.
I try to maintain compatibility with FPP in my anticrash, which isn't possible because of this.

The same applies for all the functions I mentioned.
All these functions are getting shadow blocked from getting called, because of FPP.

Sorry, if I sound pissed, but I tried to figure out, why my anti crash tends to not work in certain cases, which took me extremely long and now I'm pretty pissed after I found out, it's not even my fault.

So why should this behaviour change and what impact could a change mean?
The behaviour has to change, because otherwise addons don't work, because FPP returns false/true/dickvar for whatever reason in their hooks.
The impacts are none to be honest, just all currently blocked hooks will work then.

Also, it's pretty easy to fix.
Just don't return anything.
The gamemode itself calls most, when not all functions like PhysgunPickup on entities itself after all regular hooks have been called.

Btw. also I don't understand code like in line 170.
It just doesn't add up why a blank "return" was put there.

Line 674, I think they fixed this with a error message.

**Comment by FPtje** [comment]
Do you realize that returning a boolean in hooks like PhysgunPickup, CanTool and all those other hooks are literally how FPP makes sure players are prevented from using physgun and tool and whatnot?

I realise that other hook listeners may not get called, but returning values in those hooks is literally what makes FPP work.

**Comment by mcNuggets1** [comment]
Not in the cases I mentioned.
Did you read and understood my worries?
You return too early, the Gamemode would do it itself, but you do it earlier, even thought it doesn't serve any sense, because it would do the same after all hooks were called

**Comment by mcNuggets1** [comment]
Also you could just not return something, instead of returning something.
You just defeat any modding ability with this handling, while it could be done different.

**Comment by roboderpy** [comment]
This is not something possible with default GLua api what you are asking about.

Use custom hook implementations with priorities, BlitzHook, DLib's Hook or ULib's hook for example.

**Comment by FPtje** [comment]
What do you mean return early? Do you mean as opposed to at the end of a function? Because that would make no difference.

I also don't understand what you mean with the gamemode doing it itself. Gamemode functions get called after the hooks. They also get suppressed when a hook returns. I'm not sure how gamemode functions fit in this story.

Also, to reply to your second post. I MUST return something, otherwise FPP will literally stop doing the single most important thing it was made for: preventing players from touching shit they aren't allowed to touch.


Go on and remove all return statements in FPP and find your server being in chaos because everyone is fucking with other people's props.

**Comment by mcNuggets1** [comment]
We are misunderstanding each other.
FPP returns a boolean, when it doesn't need to.
It uneccessary blocks Hook calls. I even explained an example.

**Comment by roboderpy** [comment]
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L133

If entity explicitly want PhysgunPickup hook to return true, FPP does so. For me, it seems reasonable

**Comment by mcNuggets1** [comment]
So in line 132 it doesnt need to stop execution of all hooks.
It could just Return blank, then after every hook ran, the gamemode dös the same.

**Comment by roboderpy** [comment]
no. https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/gamemodes/sandbox/gamemode/shared.lua#L121

**Comment by mcNuggets1** [comment]
But that's what I'm trying to say.
The gamemode runs the hook in the end.
FPP could just use it to check if it returns something and if it doesn't it just returns blank instead of ceasing all hook calls.

**Comment by mcNuggets1** [comment]
But I never meant, remove all return statements in all of FPP's hooks system.
That wouldn't even make any sense.

**Comment by roboderpy** [comment]
in my old code, [i do the same thing](https://github.com/roboderpy/DPP/blob/master/lua/dpp/sh_hooks.lua#L224) but [i return only false on hooks](https://github.com/roboderpy/DPP/blob/master/lua/dpp/sh_hooks.lua#L94)

hmmm

**Comment by mcNuggets1** [comment]
https://github.com/mcNuggets1/mg_anticrash/blob/master/lua/mg_anticrash/sv_anticrash.lua#L64-L65

I do it this way.
My anticrash uses the function to determine if MY code should go on.
But it doesn't return FALSE or TRUE in any hooks, only if it really needs to forbid something.

**Comment by FPtje** [comment]
FPP returns true when it wants to explicitly allow something. It returns false when explicitly denying something. It returns no value when not making judgement. That is proper hook etiquette.

> Of course it has to return booleans or values sometimes, but not if the gamemode itself already decides this stuff.

What the gamemode decides is irrelevant. FPP needs to return values to work.

**Comment by mcNuggets1** [comment]
I'm trying to reason.

Ok I'll repeat again.
There is a function called "PhysgunPickup" which can be written onto entities.

Making it looks like this:

function ENT:PhysgunPickup()
     return self:IsOkay()
end

The gamemode itself (sandbox) will run this function, when all other hooks have run.
But then comes FPP across and runs it too and even returning it's value, before giving other hooks the attempt to make their own calls.
I'm just politely asking for this behaviour to change and not TO return any values, until the gamemode itself does it, it can still be used to check if FPP's code goes on however.
This behaviour is making the work with custom entities extremely difficult, because of FPP.

But it's not like FPP only does it once for PhysgunPickup, no.
It does it for every other entity related function either.

And that's my problem.
Not that FPP is returning values, but that FPP is ceasing all hook calls, because an entity has a function written onto it.

**Comment by mcNuggets1** [comment]
I suck ass at explaining, I have to admit.

**Comment by FPtje** [comment]
So you're specifically talking about the entity functions? Could you link to sandbox implementations? They definitely weren't there when this was implemented.

**Comment by mcNuggets1** [comment]
https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/gamemodes/sandbox/gamemode/shared.lua#L120-L122

**Comment by mcNuggets1** [comment]
Here are the specific overrides:
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L132-L137
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L159-L164
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L175-L180
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L192-L201
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L214-L223
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L237-L246
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L263-L268
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L285-L290
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L465-L470

Also this should be fixed in GMod now.
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L674-L683

And this doesn't make any sense.
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L517

And this just returns something for the sake of returning, while return false would be enough:
https://github.com/FPtje/Falcos-Prop-protection/blob/master/lua/fpp/server/core.lua#L521-L526

**Comment by FPtje** [comment]
One major difference between sandbox' implementation and mine is that mine supports setting booleans directly. e.g. `ent.PhysgunPickup = false`. Removing this stuff might break stuff. Especially since IIRC I probably use that in DarkRP.

**Comment by mcNuggets1** [comment]
Then return false/true when it's set to something, but not when the function is called.

**Comment by FPtje** [comment]
I see nil checks before returning. What am I missing?

**Comment by mcNuggets1** [comment]
I just want a possible added function to not stop all code execution.
If it's a bool you could handle it different, but please not with functions.
Anyways I'm gone for the day.
So I will answer back tomorrow.

**Comment by FPtje** [comment]
> I just want a possible added function to not stop all code execution.

This is not in the scope of DarkRP. It's a fundamental problem with hooks.

**Comment by mcNuggets1** [comment]
The problem I have is:
I expect things to work in sandbox/darkrp without FPP the same as with FPP, development wise
By returning values too early for something which is actually called last, is making my anticrash addon malfunction. 
If its a boolean, i'm fine with returning values but not when it is a function, because that's breaking compatibilty for no real reason.

**Comment by mcNuggets1** [comment]
By the way this also breaks ghosting.
Entities with a physgunpickup function written onto them and being ghosted ON spawn, can't be unghosted, thus breaking the entity making it non solid for eternity.

**Comment by FPtje** [comment]
Problem here is, though, that changing this would make it harder for entities to override FPP's behavior. 

Say you have an entity with `function ENT:PhysgunPickup(ply) return true end`, and FPP decides that some player can **not** pick up the entity. Currently, that player can pick up the entity, as the function is tested before FPP's judgement is made. Changing the behavior to only check for bools means that turns around. 

I'd rather not get bug reports about people updating FPP to find out they suddenly can't touch their entities anymore, or the other way around.

**Comment by mcNuggets1** [comment]
Run the function to check for some return.
If it returns something other than nil, STOP FPP's code, if not, let it proceed.
This way other code can be executed, but it still checks for being abel to run.

**Comment by FPtje** [comment]
I pushed a commit changing some things. Other things have been denied. Specifically, the `GravGunPickup` is implemented as `GravGunPickupAllowed` in the base gamemode, so I'll *have* to return the value lest I break the `GravGunPickup` entity function. 

Also your "Nonsense" case. The return there nicely documents that FPP defers judgement. Removing it would not affect functionality, so might as wel leave it in for documentation.

**Comment by mcNuggets1** [comment]
Oh ahem.
OnPhysgunPickup hook makes it into the game next update.

I wouldn't override GravGunPickup, because some addon authors might use it.
Same goes for PhysgunPickup.

It's safer to just not return anything with these functions tbh.

**Comment by FPtje** [comment]
That wasn't there yet? Does that mean there were other people talking about this stuff? Surely otherwise it would be too coincidental. The other functions have been there for years.

**Comment by mcNuggets1** [comment]
The same day I opened up this issue, I've created this request.
https://github.com/Facepunch/garrysmod-requests/issues/1353

So, if you don't fix the behaviour, I can just hook into the new hook, haha.
