### ISSUE TITLE
Sort buddies/player list alphabetically

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/Falcos-Prop-protection#251]
Currently it's very hard to find specific players in list.
Sorting them alphabetically would solve this.

**Comment by FPtje** [comment]
Done. Also life hack: Clicking on column names in list views sorts stuff.

**Comment by mcNuggets1** [comment]
What about the players list in cleanup disconnected player props?

**Comment by FPtje** [comment]
It bothers me that you've apparently waited with that until after I replied.

**Comment by mcNuggets1** [comment]
I thought you know.

**Comment by FPtje** [comment]
So you ask me to sort the buddies list, and you expect me to "know" about cleanup players list?

**Comment by mcNuggets1** [comment]
The thread name is sort buddies/player-list.
I thought you know, the player list is seperate.

**Comment by FPtje** [comment]
The buddies list is a player list. It wasn't clear that you were referring specifically to the player list of the cleanup menu.

**Comment by mcNuggets1** [comment]
Yeah, sorry for that then.
