### ISSUE TITLE
Owner world 

### ISSUE THREAD

**Issue by michak89** [FPtje/Falcos-Prop-protection#252]
Hello

I know this is prop protection addon but would it be possible to add ownership and spam protection for toolgun spawned guns?  I see an option to block duplicator on those, nothing else. 
It's easy way to lag and crash any server with enabled weapon spawning. 

https://i.imgur.com/DQwLyOa.jpg

:cactus:

**Comment by FPtje** [comment]
Looks like spawned weapons aren't added to undo or cleanup. That's a nice GMod bug for someone to report I suppose. Until then, there's a workaround in FPP.
