### ISSUE TITLE
FPP undoes tool restrictions after each restart

### ISSUE THREAD

**Issue by RadioactvePixels** [FPtje/Falcos-Prop-protection#253]
The title says it, after applying restrictions to many tools in the Tool restriction category, they reset after each server restart.

**Comment by FPtje** [comment]
How many tools is too many?

**Comment by RadioactvePixels** [comment]
I don't know. I was just saying I applied the restriction to many different tools.

**Comment by FPtje** [comment]
I set the tool restriction for 3000 (fake) tools, and some real ones. When I restarted my server and tried to load the tool restrictions for the real tools, they loaded just fine.

The code I ran:
```
lua_run_cl for i = 1, 3000 do timer.Simple(i * 0.01, fp{RunConsoleCommand, "FPP_restricttool", "test-tool-" .. i, "admin", "1"}) end
``` 

Tried the same with MySQL. Cannot reproduce.
