### ISSUE TITLE
PlayerSpawnedSENT isn't used

### ISSUE THREAD

**Issue by thegrb93** [FPtje/Falcos-Prop-protection#254]
Causes things created with PlayerSpawnedSENT without cleanup or undo to not be assigned an owner.

**Comment by FPtje** [comment]
Should be caught by undo. What entity are we talking about here that doesn't add to undo?

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/blob/master/lua/starfall/libs_sh/holograms.lua#L105

**Comment by roboderpy** [comment]
in code above you also don't call `PlayerSpawnSENT`

**Comment by thegrb93** [comment]
If someone requests a way to block holograms with PlayerSpawnSENT then I'd add it.
