### ISSUE TITLE
Constrained Error

### ISSUE THREAD

**Issue by tomekb530** [FPtje/Falcos-Prop-protection#255]
Hi, i found that when something is roped to the world it becomes constrained and not movable, i repaired it by `if ent and ent.GetClass and hardWhiteListed[ent:GetClass()] then return true, reasonNumbers.world end` in lua/fpp/server/ownability.lua at calculateCanTouchFunction just above IsValid check (idk why gmod returns IsValid(Entity(0)) as false)

**Comment by FPtje** [comment]
![hl2_2019-08-24_16-36-11](https://user-images.githubusercontent.com/1202014/63638837-604f2a00-c68d-11e9-82a4-15de91c543a0.jpg)

Cannot reproduce. I've set all "Admin can touch world props" and "Admin can touch blocked props" off.
