### ISSUE TITLE
Group And Tool restrictons

### ISSUE THREAD

**Issue by WoodyTheMighty** [FPtje/Falcos-Prop-protection#257]
Hi,
So i have a problem where on my server the group tool restrictions and tool restrictions dont save when the server gets restarted
any way of making it save?

**Comment by FPtje** [comment]
Some error is preventing it from loading, probably. Either way check the errors and resolve those. By default FPP doesn't have this problem.

**Comment by WoodyTheMighty** [comment]
there are no lua errors

**Comment by FPtje** [comment]
I cannot reproduce the bug, so I cannot help you.

**Comment by WoodyTheMighty** [comment]
i got a question
would it be a problem where because the fpp file is not saved in the server as a file by it self but subscribed from steam community
would that be the cause

**Comment by FPtje** [comment]
No, those versions are exactly the same.

**Comment by WoodyTheMighty** [comment]
but maybe something is stopping it from saving in the community workshop version because it gets automatically updated bu workshop

**Comment by FPtje** [comment]
No. Shit is saved in your database, `sv.db`. Only the code is from the workshop. Your settings are not affected by workshop updates.

**Comment by WoodyTheMighty** [comment]
do you know how to access the files of it through a server host if it was subscribed from steam workshop

**Comment by FPtje** [comment]
`sv.db` is in the root of the garry's mod dir. It's an SQLite file. Use some SQLite program to read it. Workshop addons were installed as `.gma` files in the `addons` directory.

Seriously, though, looking at those files will not resolve your problem. Most likely cause is some addon messing up startup hooks by either throwing an error or returning a value.

**Comment by WoodyTheMighty** [comment]
i jsut realized the only one that is not saving is the tool restricitons the rest save

**Comment by WoodyTheMighty** [comment]
would urs make it not work?

**Comment by FPtje** [comment]
I don't know. Possibly.

**Comment by WoodyTheMighty** [comment]
i also have one more problem where if i press on a groups name in group tool restrictions and i then press the allow all tools by default box it says group does not exist
any ideas

**Comment by WoodyTheMighty** [comment]
this is the problem im having exacly just took a vid of it

![Problem](https://user-images.githubusercontent.com/54628093/63864433-bed71980-c9a7-11e9-9683-0b6d3126c327.gif)

**Comment by FPtje** [comment]
I'd say the combination of odd problems seems to indicate some loading problem, but I'm not sure what could cause that kind of stuff other than what I already said.
