### ISSUE TITLE
help

### ISSUE THREAD

**Issue by CLEVELANDMAN99** [FPtje/Falcos-Prop-protection#258]
I'd like to add this to my server so I can use MySQL, but my server is already defaulted with FPP. What do I do?

**Comment by FPtje** [comment]
You can set MySQL settings in the `lua/config` directory.

**Comment by CLEVELANDMAN99** [comment]
> You can set MySQL settings in the `lua/config` directory.

I don't have config in my directory, I don't even have a FPP directory. It's just already on my server, don't even have it in my workshop collection.

**Comment by FPtje** [comment]
Are you running DarkRP? Because then FPP takes DarkRP's MySQL config
