### ISSUE TITLE
Gmod Buttons Get Removed with Adv-Dupe

### ISSUE THREAD

**Issue by Potatosayno** [FPtje/Falcos-Prop-protection#260]
Hey,
I noticed when duplicating a creation I did, FPP would remove some of the buttons for "Prop Spam".
This happened on the default Garry's Mod Buttons, I'm using Adv-Dupe 2.
This doesn't happen with other stuff that I tried like keypads, but it does with Gmod buttons.

**Comment by FPtje** [comment]
Is there a way you can upload the dupe file?

**Comment by Potatosayno** [comment]
Sure thing, hold on.
[hospital.txt](https://github.com/FPtje/Falcos-Prop-protection/files/3864847/hospital.txt)

The buttons at the top on the doors disappear once I spawn them with FPP Spam on. (because "I spawn them too fast")
But you can also get the same reaction by simply duplicating multiple buttons at the same time normally.

**Comment by FPtje** [comment]
It looks like it's a bug in Advanced Duplicator 2 that manifests itself in FPP.

See https://github.com/wiremod/advdupe2/issues/265

**Comment by FPtje** [comment]
I've worked around this with `debug.trace`. It's not the prettiest or most stable solution, but I think it should cover all the cases. You can post in this issue or create a new one if you find situations where it doesn't work.

When @thegrb93 implements the global I'll prefer using that, as it is a more stable solution that doesn't break when function names are changed or the stack trace gets larger than 15.

**Comment by michak89** [comment]
Hello, I experience same problem on newest FPP version with advanced duplicator 2.
My dupe file: https://www.dropbox.com/s/ecc31j4yhsc9drf/final_mech.txt?dl=0

No idea what's wrong :/
