### ISSUE TITLE
Lua Error On Startup

### ISSUE THREAD

**Issue by Joeburglar** [FPtje/Falcos-Prop-protection#262]
[Falco's Prop Protection (FPP)] lua/fpp/server/settings.lua:409: bad argument #1 to 'pairs' (table expected, got nil)
1. pairs - [C]:-1
2. AddDefaultBlocked - lua/fpp/server/settings.lua:409
3. AddEntity - gamemodes/liquidrp/gamemode/makethings.lua:132
4. unknown - gamemodes/liquidrp/gamemode/addentities.lua:20
5. include - [C]:-1
6. unknown - gamemodes/liquidrp/gamemode/init.lua:132

**Comment by Bo98** [comment]
This is a problem with LiquidRP rather than FPP. It incorrectly calls an FPP function with nil data.

**Comment by Joeburglar** [comment]
Would there be anyway to fix this?

**Comment by FPtje** [comment]
From LiquidRP, yes, from FPP, no.
