### ISSUE TITLE
BLACKLIST

### ISSUE THREAD

**Issue by wolfi9431** [FPtje/Falcos-Prop-protection#263]
every prop i blacklist keeps dissapearing after restart no props in blacklist nomore

**Comment by FPtje** [comment]
Not a help forum, insufficient info to reproduce bug

**Comment by wolfi9431** [comment]
well where tf do i fix this then

**Comment by FPtje** [comment]
Forum.darkrp.com is full of people with that same problem. Do a search there, you might find some answers

**Comment by wolfi9431** [comment]
did theres literally nothing i found
