### ISSUE TITLE
FPP Creating Script errors.

### ISSUE THREAD

**Issue by BooperNoodle** [FPtje/Falcos-Prop-protection#267]
Whenever i try to spawn in any item that isn't blacklisted it creates script errors and it deattaches any thrusters and other from props and it says this whenever i spawn an item, here is an example; "
[Falco's Prop Protection (FPP)] lua/fpp/server/core.lua:70: attempt to index global 'AdvDupe2' (a nil value)
  1. Add - lua/fpp/server/core.lua:70
   2. AddCleanup - gamemodes/sandbox/gamemode/player_extension.lua:93
    3. GMODSpawnProp - gamemodes/sandbox/gamemode/commands.lua:223
     4. unknown - gamemodes/sandbox/gamemode/commands.lua:30
      5. unknown - lua/includes/modules/concommand.lua:54

Leonard L. Church<STEAM_0:0:53424359> spawned model models/props_borealis/borealis_door001a.mdl
Requesting texture value from var "$basetexture" which is not a texture value (material: pp/copy)" 

this only started today, maybe its the version of gmod i have which is for chromium
![image](https://user-images.githubusercontent.com/59547433/71791421-f6fc0200-3002-11ea-871d-e4cf99886d7a.png)  
![image](https://user-images.githubusercontent.com/59547433/71791438-0418f100-3003-11ea-905d-fdce0a780891.png) if this bug isn't fixed i'm afraid i'll have to remove it from my hosting server entirely. 

. It also makes it impossible to remove the thrusters as well.

**Comment by BooperNoodle** [comment]
Sorry if the screenshots look horrible.

**Comment by BooperNoodle** [comment]
what i forgot to add was, it also makes removing items hard, the z button refuses to work when the script error happens and yes i binded my delete key to Z.

**Comment by FPtje** [comment]
Fixed
