### ISSUE TITLE
FPP detects props through walls

### ISSUE THREAD

**Issue by mcNuggets1** [FPtje/Falcos-Prop-protection#269]
FPP detects props through walls titled as "world".

https://i.imgur.com/0csEmig.png

**Comment by FPtje** [comment]
Let's hope this doesn't cause certain weird entities not to show ownership

**Comment by mcNuggets1** [comment]
Why not just use a simple trace line?

**Comment by FPtje** [comment]
Because a simple traceline is exactly what was removed in #264 

The difference between a simple trace and this is being able to see the owner of faded doors and other weird entities.
