### ISSUE TITLE
freeze everything

### ISSUE THREAD

**Issue by dick8888** [FPtje/Falcos-Prop-protection#272]
hey,

because of the prop protection  (i think if people spawn vehicles, idk) WAC helicopters get freezed aswell, can i somehow exclude them from getting freezed by the protection.

it happens sometimes (very annoying if you are mid air)
do you think it could work if I move WAC (which counts as a entities) from entities to vehicles somehow ?

best regards,
dick8888

**Comment by FPtje** [comment]
I didn't notice any freezing with WAC vehicles. Note that if they are being frozen in mid air, it's probably not FPP. FPP freezes when you spawn things. Not at random times while you're not spawning things.

I think it's something else.
