### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by Corprosss** [FPtje/Falcos-Prop-protection#273]
Im sorry for asking this but im an beginner for server coding how can i avoid prop surfing in my server

**Comment by FPtje** [comment]
Well, FPP is definitely not made for that. There are plenty of anti prop surfing addons out there, but they make prop handling really annoying in my opinion.

I always have this radical idea of just letting people prop surf. You can get to odd places by building bases and with fancy SWEPs anyway, so why bother banning prop surfing?
