### ISSUE TITLE
F4 Entity bug

### ISSUE THREAD

**Issue by WillisAwesome** [FPtje/Falcos-Prop-protection#274]
When players buy an entity it becomes a world prop how do I fix this.

**Comment by FPtje** [comment]
This might be intended. Does it negatively affect gameplay in any way?

**Comment by WillisAwesome** [comment]
Well, I'm trying to make it owned by the said player is there a way to change it so it can be like this?

**Comment by FPtje** [comment]
Why do you want it?

**Comment by WillisAwesome** [comment]
I'm trying to make so they have the ability to physgun the entity they bought.

**Comment by FPtje** [comment]
Use the `playerBoughtCustomEntity` hook and use `CPPISetOwner`.

**Comment by FPtje** [comment]
You can decide which entities are owned by the player, because I suppose you don't want that for all entities.
