### ISSUE TITLE
My props don't belong to me anymore

### ISSUE THREAD

**Issue by SuperTemich2005** [FPtje/Falcos-Prop-protection#277]
For some reason, owner of my props changed and now they belong to "Constrained".

That happens a lot of time and annoying! I had to rebuild my base five times!
Buddies can interact with my props, though. How do I reclaim my props?
![image](https://user-images.githubusercontent.com/39464061/80305604-69693b80-87c6-11ea-9725-b78f52c46722.png)

I don't know version of the mod. Garry's mod build is march 2020(aka latest, because I play steam version, not hacked one).
Steps to reproduce: dunno, it happens by itself randomly.

**Comment by SuperTemich2005** [comment]
If you need any more info, say it, I'll add new info or do something else.

**Comment by FPtje** [comment]
Means there's an entity constrained to your entity that you cannot touch.

**Comment by SuperTemich2005** [comment]
Got it, thank you.
