### ISSUE TITLE
Group doesnt exist

### ISSUE THREAD

**Issue by WindingDuke77** [FPtje/Falcos-Prop-protection#278]
When i try to edit tool restriction it comes up with that at the bottum. This is massive problem as the group i cant edit has "allow all tools by default" ticked

**Comment by FPtje** [comment]
Cannot reproduce.

**Comment by WindingDuke77** [comment]
any way i can show it to you in server

**Comment by FPtje** [comment]
Can you delete and recreate the group?

**Comment by WindingDuke77** [comment]
yeh i can delete the group but when i load groups it just comes pack
