### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by BearRP** [FPtje/Falcos-Prop-protection#282]
Hey im trying to make a prop whitelist but when i reset the server the default blacklisted props show back up, Everything else saves fine but i cant remove the default props that are already in there i tried removing them in game and off the database but they just come back

**Comment by FPtje** [comment]
When there are no blocked models, FPP assumes the default ones have not been loaded yet. Make sure at least ONE blocked model is in there after you cleared the original list out. Then it won't reset.

**Comment by BearRP** [comment]
I have stuff on my blacklist already it just keeps readding the default props to it
