### ISSUE TITLE
Players can damage NPC

### ISSUE THREAD

**Issue by Tosiek99** [FPtje/Falcos-Prop-protection#285]
Regardless of whether the "Entity damage protection" is enabled or not, players can kill NPC's anyway. I mean VCMod car dealer npc, weed buyer npc, everyone of them. Need fast help.

**Comment by FPtje** [comment]
It's not FPP, the issue is explained here by @FlorianLeChat:
https://github.com/FPtje/DarkRP/issues/3091#issuecomment-770231399
