### ISSUE TITLE
Tool restriction is not working properly

### ISSUE THREAD

**Issue by Tosiek99** [FPtje/Falcos-Prop-protection#286]
When i try to enable "Physprop" for everyone, players, can't use it. 
![image](https://user-images.githubusercontent.com/78603704/107049492-7346b300-67ca-11eb-8a55-7e42ba5d5e16.png)
When i try to allow it for one player, it will work. What to do?

**Comment by FPtje** [comment]
What message do players get when trying to use it?

**Comment by Tosiek99** [comment]
Tool restricted! Incorrect group.

**Comment by FPtje** [comment]
There's also group tool restriction, perhaps someone has changed group tool restriction settings for the `physprop` tool.

**Comment by Tosiek99** [comment]
![image](https://user-images.githubusercontent.com/78603704/107050474-8e65f280-67cb-11eb-87d4-e169a7e9c44a.png)

**Comment by FPtje** [comment]
And is the group tool restriction a blacklist or whitelist?

**Comment by Tosiek99** [comment]
![image](https://user-images.githubusercontent.com/78603704/107050713-d8e76f00-67cb-11eb-88b2-402becd0072e.png)
How to check it?

**Comment by FPtje** [comment]
You just did. It's the `Allow all tools by default` checkbox. Looks like the UI isn't too clear, but I think then "Tools currently in user" actually means that those are the exceptions to the "Allow all tools by default" rule. So those tools are NOT allowed to be used by players with usergroup `user`.

The solution should be taking `physprop` out of the list of "Tools currently in user".

**Comment by Tosiek99** [comment]
Oh my god, it work's. Thanks a lot! FIXED
