### ISSUE TITLE
Physgun reload protection is ENABLED but don't work, also props after scrolling don't stop

### ISSUE THREAD

**Issue by Tosiek99** [FPtje/Falcos-Prop-protection#287]
As in topic.
![image](https://user-images.githubusercontent.com/78603704/107053052-adb24f00-67ce-11eb-949e-834f76aa96d8.png)
Everyone can do it. Admins and players. How to prevent it?

**Comment by FPtje** [comment]
With "props after scrolling don't stop" I suppose you mean prop kill prevention. FPP doesn't do prop kill prevention.

People still being able to use Physgun Reload probably means some other addon is messing it up.
