### ISSUE TITLE
Players have "blocked" on other players props

### ISSUE THREAD

**Issue by Tosiek99** [FPtje/Falcos-Prop-protection#288]
These our my settings for physgun protection
![image](https://user-images.githubusercontent.com/78603704/107061301-4dc0a600-67d8-11eb-9981-0157885256f7.png)
Players report that they don't see props owner.
How to fix it?

**Comment by FPtje** [comment]
If the thing says "blocked" then the props are on some blocked list. If you really can't find it, you can run `FPP_ResetAllSettings`, which will clear ALL settings to the default value, and set it up again.
