### ISSUE TITLE
Players see blocked when they have pocket or weapon.

### ISSUE THREAD

**Issue by Tosiek99** [FPtje/Falcos-Prop-protection#289]
No nickname when using pocket:
![image](https://user-images.githubusercontent.com/78603704/107160039-139c0380-6994-11eb-9f85-99960df705fa.png)
Nickname when using physgun:
![image](https://user-images.githubusercontent.com/78603704/107160059-37f7e000-6994-11eb-9a6b-5769c77f8f27.png)

I need to know how to make see player's prop when holding pocket or weapon. Or to know if there is such an option.

**Comment by FPtje** [comment]
You can't. Different weapons have different controls. The text on the left reflects that.
