### ISSUE TITLE
SAM and FPP error

### ISSUE THREAD

**Issue by timothybvf** [FPtje/Falcos-Prop-protection#292]
When I join my server I get this error:
[Falco's Prop Protection (FPP)] lua/fpp/client/hud.lua:188: attempt to index local 'eyeTrace' (a nil value)
    1. func - lua/fpp/client/hud.lua:188
        2. unknown - addons/sam-137/lua/includes/modules/hook.lua:198

**Comment by FlorianLeChat** [comment]
AFAIK, [GetEyeTrace](https://github.com/FPtje/Falcos-Prop-protection/blob/c7fc26d1dc3f14b43c5cd2f0d383636b3a0191b8/lua/fpp/client/hud.lua#L188) may return nil in some cases (as it uses [util.TraceLine](https://wiki.facepunch.com/gmod/util.TraceLine) internally, the easiest thing to do is to simply check the value before doing any distance calculations, this should be quick for Falco 👍
