### ISSUE TITLE
Error with MySQL & SV.DB

### ISSUE THREAD

**Issue by AlexandreSama** [FPtje/Falcos-Prop-protection#297]
Hello ! 

I have configured FPP at the _MySQL.lua level but nevertheless it still uses sv.db!

I am running a DarkRP server and DarkRP is also configured on a DB, except it works fine.

Did you know why?

Btw I don't have any errors in the console and I don't even have any logs 

Also, I downloaded the FPPDebug version present in the github release to put it in garrysmod / addons because strangely, I had no file when I took it in the Steam Workshop 

Edit 1 :

I deduced that FPP can no longer connect to the BDD, I tried with an empty BDD to see but nothing helped

**Comment by FPtje** [comment]
Not a help forum

**Comment by AlexandreSama** [comment]
So tell me where i could have help ?

**Comment by FlorianLeChat** [comment]
https://discord.gg/gmod
