### ISSUE TITLE
Need help setting up.

### ISSUE THREAD

**Issue by BGiPV** [FPtje/Falcos-Prop-protection#299]
I have ULX and your addon installed on my server. How to take away functions from admins: touch player props and interact with player props using a tulgan. And is it possible to give such opportunities ONLY to certain groups.
Translate by Google Translator

**Comment by FlorianLeChat** [comment]
You can find help on the [DarkRP](https://darkrp.page.link/discord) or [Garry's Mod](https://discord.com/invite/gmod) Discord, but this place is for bug reports only.
