### ISSUE TITLE
How do give access to a player so that he can add props to the blacklist?

### ISSUE THREAD

**Issue by Star-Butterfly** [FPtje/Falcos-Prop-protection#300]
The option with granting rights to FPP_Settings is not suitable.

**Comment by FlorianLeChat** [comment]
The person needs to have administration permissions (A.K.A `admin` or `superadmin`) but this is clearly not the place to get help, this directory is only for bug reports. Use the [DarkRP](https://darkrp.page.link/discord) or [Garry's Mod](https://discord.com/invite/gmod) Discord instead.

**Comment by Star-Butterfly** [comment]
> The person needs to have administration permissions (A.K.A `admin` or `superadmin`) but this is clearly not the place to get help, this directory is only for bug reports. Use the [DarkRP](https://darkrp.page.link/discord) or [Garry's Mod](https://discord.com/invite/gmod) Discord instead.

Hmm, thanks for the redirect. Only I don't have DarkRP:/

**Comment by FlorianLeChat** [comment]
That's okay, since FPP is built into DarkRP by default, the people who use it are familiar with the system and possibly also better able to answer your questions/problems.
