### ISSUE TITLE
the blocked models list is not showing any of the models

### ISSUE THREAD

**Issue by sparky148** [FPtje/Falcos-Prop-protection#308]
my blocked models list isn't showing any of the models and I want to remove a lot of the models on there is there an easy way to fix this or remove all the models

**Comment by FPtje** [comment]
What exactly do you mean by not showing any of the models? Is the list empty, or does it only not show the models you added?

Either way please check for errors in the server startup log and in your own console. I'll need to know more details to make an assessment of what's going on.

For resetting there's always the fpp_resetallsettings command

**Comment by sparky148** [comment]
yeah the list is empty and isn't showing the the models I added ill just restet all settings thanks
