### ISSUE TITLE
Duplicator antispam prevents also copying.

### ISSUE THREAD

**Issue by michak89** [FPtje/Falcos-Prop-protection#309]
Hi, when i try to copy something from my buddies with area copy and not selecting "copy only my props" in advdupe2.
This setting: 
![1x](https://user-images.githubusercontent.com/40716529/181357214-20e19aba-e157-4e6f-9f66-97ad51ff1142.png)

  makes copying imposible with antispam message spam, it looks like this: 

![16710716 56000003_image](https://user-images.githubusercontent.com/40716529/181357242-752649c0-6911-4853-9d34-aa7b79717cca.png)

I did not check but asume this somehow adds rate limiting to SANDBOX:CanTool hook. There is an argument saying what tool button was pressed, could this be a workaround to avoid spam prevention when tools are duplicator and advdupe2 with right (copying) button?

Area copy in advdup2 works like clicking right button on all props one by one.

<3

**Comment by FPtje** [comment]
Wouldn't that just make an exception for antispam that allows people to spam?

**Comment by michak89** [comment]
Oh, so it works like that on purpose, i tought it should only prevent dupe
pasting / object creation spam...

Thing is im not able to copy anything, im not spamming with copy button,
one right click with area copy results in spam prevetion on copying each
prop in area.

Sorry to bother if its working as intended.

śr., 27 lip 2022, 23:01 użytkownik Falco Peijnenburg <
***@***.***> napisał:

**Comment by FPtje** [comment]
Looking at some code that FPP uses, advdupe2 sets some global variable called `AdvDupe2.SpawningEntity`, that FPP reads to recognise that something is not just spawning individually, but spawning by being a duplicated thing.

https://github.com/FPtje/Falcos-Prop-protection/blob/4fc7ff98e1cdad152531742262c6977012d7c52d/lua/fpp/server/core.lua#L72-L74

I think in advdupe2 this variable is set for most methods of spawning a duplication, but not in this specific case. In that case I would say: ask the developers of advdupe2. For FPP I don't think there's much to do.
