### ISSUE TITLE
Darkrp Shipment and others not being owned

### ISSUE THREAD

**Issue by KyberNetworks** [FPtje/Falcos-Prop-protection#313]
Shipment and ammo are not being owned by the player when they buy it from f4 it is owned by the world how do i fix this

**Comment by KyberNetworks** [comment]
This effects the gameplay as people cant phsgun it as its a world owned ent and if we let everyone beable to move world ents they will move perma props and npcs that are owned by the world

**Comment by FPtje** [comment]
Sounds like you don't have the models. You may need to make sure css is installed.
