### ISSUE TITLE
Suggestion: Update console commands to use SteamID instead of UserID

### ISSUE THREAD

**Issue by AshleyJamesy** [FPtje/Falcos-Prop-protection#321]
The reason I ask for this is so Wiremod E2 can run console commands to Share props.
Currently the console commands use UserID which is data the E2 doesn't have any functions to get from the Player.
  
https://github.com/FPtje/Falcos-Prop-protection/blob/5d8e657cf643364704ac57c12f006680b2bf98c8/lua/fpp/client/menu.lua#L1224  
  
Here is an example of how I would use it in E2
```lua
function void entity:fppShare(Player:entity, Share:number) {
	if(Player:isValid() && Player:isPlayer()) {
		concmd("FPP_ShareProp " + This:id() + " " + Player:steamID() + " " + (Share > 0))
	}
}
entity():fppShare(findPlayerByName("John Doe"), 1)
```

I know there could be some addons out there to add fpp functions to E2, but this would allow it to work on any server

I already have a function for sharing the prop globally, but not for specific players
```lua
function void entity:fppShare(Type:string, Share:number) {
	if(This:isValid()) {
		switch(Type) {
			case "physgun",
				concmd("FPP_ShareProp " + This:id() + " SharePhysgun1 " + (Share > 0))
			break
			case "gravgun",
				concmd("FPP_ShareProp " + This:id() + " ShareGravgun1 " + (Share > 0))
			break
			case "use",
				concmd("FPP_ShareProp " + This:id() + " SharePlayerUse1 " + (Share > 0))
			break
			case "damage",
				concmd("FPP_ShareProp " + This:id() + " ShareEntityDamage1 " + (Share > 0))
			break
			case "toolgun",
				concmd("FPP_ShareProp " + This:id() + " ShareToolgun1 " + (Share > 0))
			break
			default,
			break
		}
	}
}
```

**Comment by FPtje** [comment]
Why doesn't E2 have userid? That's like the simplest thing to add 😅

**Comment by FPtje** [comment]
I asked around, and someone noted that the function does exist here:
https://github.com/wiremod/wire/blob/77e14237229a1edafc08157ee234f89cd1f7678e/lua/entities/gmod_wire_expression2/core/player.lua#L114

So you should be able to just use `Player:userId`. That closes the issue. Good luck with the E2!

**Comment by AshleyJamesy** [comment]
Wow, that was added 4 months ago. This changes everything!
