### ISSUE TITLE
question, how do i unblacklist every prop

### ISSUE THREAD

**Issue by MagonYT** [FPtje/Falcos-Prop-protection#322]
it comes with my host and i have gprotect now

**Comment by FPtje** [comment]
Remove all props except for one, iirc it regenerates otherwise.

**Comment by MagonYT** [comment]
> Remove all props except for one, iirc it regenerates otherwise.

but HOW???!?!?!

**Comment by FPtje** [comment]
FPP has a section in the q menu for blacklisted props. You can just select props and remove them

**Comment by MagonYT** [comment]
theres nothing in the Q menu, is there a data file i can delete and add 1 prop

> FPP has a section in the q menu for blacklisted props. You can just select props and remove them

**Comment by FPtje** [comment]
Here's a screenshot from Google, with very convenient instructions:

![image](https://github.com/FPtje/Falcos-Prop-protection/assets/1202014/72bd184d-2dc7-41bd-bc59-e3c364218f6c)

The instructions being that you can disable the blocked models altogether.
