### ISSUE TITLE
prop car velocity issue

### ISSUE THREAD

**Issue by deathking61** [FPtje/Falcos-Prop-protection#333]
no idea why but when using your prop protection it seems the cars are now limited to 65kph or so when this addon is deleted the car speeds up fine. how can i fix?

**Comment by FPtje** [comment]
I have no idea, who is the author of your car addon and can we ask them for input?

**Comment by FPtje** [comment]
Closing issue as it is likely not FPP's responsibility. If you do have more information, feel free to post in this issue.
