### ISSUE TITLE
duplicates with wiremod dont delete and assign to world after user leaves the server

### ISSUE THREAD

**Issue by justsomeperson1** [FPtje/Falcos-Prop-protection#336]
hi i got a problem with fpp when some user that spawned a duplicate and only a duplicate with wiremod after they leave fpp doesnt delete it and assigns it to world for some reason and i dont know why

**Comment by FPtje** [comment]
Thanks for the report! It's surprising, as that has worked for quite a while. Some questions:

* is it only for some duplicates, or does it happen with all?
* do all entities of the duplicate stay, or only some? If only some remain, which entities are they exactly?
* if it's only some duplicates, could you upload one that you know goes wrong?

**Comment by justsomeperson1** [comment]
1. it happens sometimes but it started to happen 2 days ago
2. all stay
3. i will upload it later when i find it again

**Comment by justsomeperson1** [comment]
i found one 
![Снимок экрана 2024-07-20 214226](https://github.com/user-attachments/assets/07790db4-96f5-4daa-b32b-69ba6f4493d4)
i forgot to mention that these duplicates delete after sometime like 2-3 hours

**Comment by FPtje** [comment]
Thanks for the info. Do you have the duplicate file itself? That way I could try it myself.

**Comment by justsomeperson1** [comment]
i will copy it right now and send the link wait a moment please

**Comment by justsomeperson1** [comment]
i duplicated it and for some reason gmod visualizes it as a airboat seat and when i spawn it its invisible, i will upload it now

**Comment by FPtje** [comment]
No hurry. I'm quite busy these days, and likely won't have time to look at it in detail for a bit.

**Comment by justsomeperson1** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=3293064446

**Comment by FPtje** [comment]
If it started happening a couple of days ago, it's likely that something other than FPP causes the problem. FPP itself hasn't been updated in quite a bit.

**Comment by justsomeperson1** [comment]
i can send all the names of addons i got installed on the server

**Comment by justsomeperson1** [comment]
i recently installed a addon that delays some spawning of duplicates for less lag but when people spawn it still belongs to them and that assign to world thing happens sometimes after that

**Comment by justsomeperson1** [comment]
if you want you can join my server right now and look at it yourself

**Comment by FPtje** [comment]
It looks like I cannot load the dupe. The addon won't properly subscribe, and when manually downloading the addon, adv. duplicator 2 says it's an invalid format.

**Comment by justsomeperson1** [comment]
well i dont know what can cause this because i checked and none of the addons can be causing this because when it started to happen i didnt install any addons

**Comment by FPtje** [comment]
What duplicator addon do you use?

**Comment by justsomeperson1** [comment]
the default one

**Comment by FPtje** [comment]
Ah, thanks. I got the duplicate to work, but for me it does remove correctly on disconnect.

It looks like something on your server is somehow breaking FPP, for at least that entity. Since it is clear that FPP itself is not the issue, I'm afraid I cannot help you further.
