### ISSUE TITLE
Can't interact with props

### ISSUE THREAD

**Issue by logan2611** [FPtje/Falcos-Prop-protection#75]
After I installed this prop protection on my server no one can pick up or even interact with their props.

**Comment by BinaryLava** [comment]
I'm sorry FPtje but you seem to have a problem with people claiming your broken and fucked addon is broken and fucked. It seems the addon capitulates all over the floor whenever someone uses it except you.

**Comment by FPtje** [comment]
Well what can I do with reports that it doesn't work if it works absolutely fine for me? How can I fix bugs that I cannot reproduce, especially if the only information I get is *"IT DOESN'T WORK"*?

**Comment by BinaryLava** [comment]
There is one thing you could do:
Be a little nicer. That's all you need to do. You'd be surprised at the fact that people would be a lot more willing to cooperate if you were just a teeny bit nicer to them and had less of an attitude.

**Comment by FPtje** [comment]
People deserve respect, they don't get it by default.

**Comment by BinaryLava** [comment]
Yeah but they shouldn't get "getting treated like a piece of shit by someone who thinks they're better than anyone else" by default now, should they?

**Comment by FPtje** [comment]
I tried my best to help. I eventually got sick of it when he kept posting
long after we figured fpp wasn't the problem. I'm now getting sick of your
bitching. Fuck off.

**Comment by FPtje** [comment]
Also, this issue is almost a year old. Leave it.

**Comment by BinaryLava** [comment]
That is just downright rude. You really need to learn some manners.

**Comment by FPtje** [comment]
Not before you learn to fuck off.

**Comment by BinaryLava** [comment]
Wow. This isn't even good anymore. You're literally making me laugh my ass off at the fact that you think you're higher than everyone else.

**Comment by FPtje** [comment]
I am in my own repository, allow me to demonstrate.

**Comment by Flimsy-Fox** [comment]
I had the same problem in Single Player. The only way I fixed it is by completely restarting the game. I would back up your server, and then completely delete it, then restart it.
