### ISSUE TITLE
Unknown Player Issue

### ISSUE THREAD

**Issue by deinemudda32** [FPtje/Falcos-Prop-protection#90]
I get this lua error, as I updated FPP to the newest version today

And also every player prop is named as "Unknown Player"

[ERROR] lua/autorun/sh_cppi.lua:83: attempt to call field 'PlayerCanTouchEnt' (a nil value)
1. CPPICanPhysgun - lua/autorun/sh_cppi.lua:83
   1. updateOwnership - lua/autorun/sv_uclip.lua:35
   2. checkOwnership - lua/autorun/sh_uclip.lua:46
      1. checkVel - lua/autorun/sh_uclip.lua:173
      2. fn - lua/autorun/sh_uclip.lua:205
      3. unknown - lua/ulib/shared/hook.lua:183

**Comment by FiG-Scorn** [comment]
To those using Filezilla, ensure that your "Failed Transfers" tab is empty after every cycle, and do not do more than 3 simultaneous transfers at a time.

**Comment by Bo98** [comment]
I'm probably the only person who has never had a problem with FileZilla.

**Comment by FPtje** [comment]
Do you upload whole folders of files instead of zips?

2015-01-10 17:51 GMT+01:00 Bo Anderson <notifications@github.com>:

**Comment by Bo98** [comment]
Yep.

**Comment by FiG-Scorn** [comment]
same here.

But for critical, overnight transfers, I lower the simultaneous transfer 
cap to 1. Normaly I'll have it on 5 or 6. Default is 2 IIRC.
